from __future__ import annotations

import sqlite3
from typing import Any

from .storage import fetch_all


STATUS_DONE = "已完成"
STATUS_PARTIAL = "部分完成"
STATUS_MISSING = "未完成"
STATUS_EXTERNAL = "需要外部數據"

STATUS_WEIGHTS = {
    STATUS_DONE: 1.0,
    STATUS_PARTIAL: 0.5,
    STATUS_EXTERNAL: 0.15,
    STATUS_MISSING: 0.0,
}


def build_coverage_report(conn: sqlite3.Connection) -> dict[str, Any]:
    items = [localize_coverage_item(item) for item in coverage_items()]
    status_counts = {status: 0 for status in STATUS_WEIGHTS}
    for item in items:
        status_counts[str(item["status"])] += 1

    weighted = sum(STATUS_WEIGHTS[str(item["status"])] for item in items)
    max_score = len(items) or 1
    blocked = [item for item in items if item["status"] in {STATUS_MISSING, STATUS_EXTERNAL}]
    priority_items = sorted(
        blocked,
        key=lambda item: (int(item["priority"]), int(item["id"])),
    )[:8]

    return {
        "title": "方程式覆蓋率 / 盲點報告",
        "objective": "用來定位模型缺口，所有補洞都要用 walk-forward / out-of-sample 證明提升。",
        "status_labels": {
            "done": STATUS_DONE,
            "partial": STATUS_PARTIAL,
            "missing": STATUS_MISSING,
            "external": STATUS_EXTERNAL,
        },
        "summary": {
            "total_groups": len(items),
            "core_groups": sum(1 for item in items if item["category"] == "core"),
            "blind_spot_groups": sum(1 for item in items if item["category"] == "blind_spot"),
            "coverage_score": round(weighted / max_score, 4),
            "status_counts": status_counts,
            "database": database_snapshot(conn),
        },
        "items": items,
        "priority_next_steps": [
            {
                "id": item["id"],
                "name": item["name"],
                "status": item["status"],
                "model_risk": item["model_risk"],
                "next_steps": item["next_steps"],
                "validation_gate": item["validation_gate"],
            }
            for item in priority_items
        ],
    }


def localize_coverage_item(item_data: dict[str, Any]) -> dict[str, Any]:
    localized = dict(item_data)
    zh = COVERAGE_ZH.get(int(localized["id"]), {})
    localized.update({key: value for key, value in zh.items() if key != "data_sources"})
    if "data_sources" in zh:
        localized["data_sources"] = zh["data_sources"]
    return localized


COVERAGE_ZH: dict[int, dict[str, Any]] = {
    1: {
        "name": "馬匹基礎能力",
        "data_sources": ["參賽馬資料", "賽果資料", "HKJC 排位表 / 賽果"],
        "current_support": "已使用官方評分、負磅、年齡、性別、近期速度 / 近績及歷史賽果。",
        "gaps": "班次歷史、原始速度評分、馬匹長期能力曲線及轉倉影響仍然較淺。",
        "next_steps": "按馬場、距離、班次及日期建立標準化速度 / 能力評分，並用 walk-forward log loss 及 ROI 對照 baseline。",
        "model_risk": "高：基礎能力估錯會污染所有彩池概率。",
        "validation_gate": "樣本外 log loss、Brier、首選命中率及價值投注 ROI 必須改善。",
    },
    2: {
        "name": "近期狀態",
        "data_sources": ["賽果資料", "晨操 / 試閘資料", "HKJC 操練 / 賽果"],
        "current_support": "已使用近期名次、近期速度及操練分數。",
        "gaps": "休賽週期、復出第二 / 第三場走勢、進步 / 退步曲線及獸醫旗標仍未接入。",
        "next_steps": "加入休息日數分桶、狀態曲線斜率及長休扣分，按賽日做 walk-forward 驗證。",
        "model_risk": "高：狀態錯判會令過時評分製造假 value。",
        "validation_gate": "復出馬及近期轉勢馬的校準要改善，且 ROI 回撤不可增加。",
    },
    3: {
        "name": "距離適性",
        "data_sources": ["賽事資料", "賽果資料"],
        "current_support": "已用相近距離歷史表現計算距離適性。",
        "gaps": "增程 / 縮程效果、短途 / 一哩 / 中長途分桶及距離與步速互動仍未完整建模。",
        "next_steps": "加入距離分桶及轉程特徵，分距離檢查 ROI 及三甲命中。",
        "model_risk": "中：距離錯配會削弱排名信心及組合票。",
        "validation_gate": "分距離 Brier 及三甲命中率必須樣本外改善。",
    },
    4: {
        "name": "場地狀態及跑道適性",
        "data_sources": ["賽事資料", "賽果資料", "HKJC 排位表 / 賽果"],
        "current_support": "已把快地、好地、軟地、濕地等歷史表現轉成場地適性。",
        "gaps": "草地 / 全天候分拆、賽日中途場地變化及更細場地狀態仍不完整。",
        "next_steps": "拆開跑道類型及場地狀態歷史，等早段賽果出現後加入同日場地變化。",
        "model_risk": "中：濕地或全天候賽日會令正常評分失效。",
        "validation_gate": "場地 / 跑道分片要改善，而且不能拉低整體校準。",
    },
    5: {
        "name": "馬場及賽道",
        "data_sources": ["賽事資料", "HKJC 排位表"],
        "current_support": "賽事已儲存馬場及賽道，UI 可顯示沙田 / 跑馬地等中文名稱。",
        "gaps": "馬場 / 賽道仍未明確變成模型特徵。",
        "next_steps": "加入馬場 / 賽道特徵，並用嚴格 walk-forward 防止資料洩漏。",
        "model_risk": "中：賽道形態會影響檔位、步速及距離適性。",
        "validation_gate": "分馬場 log loss 及 ROI 要優於 baseline / 純市場版本。",
    },
    6: {
        "name": "檔位影響",
        "data_sources": ["參賽馬資料", "賽事資料", "賽果資料"],
        "current_support": "已根據參賽馬數加入內檔 / 外檔旗標。",
        "gaps": "未有按馬場、距離、欄位、賽道及即日偏差建立檔位偏差。",
        "next_steps": "按馬場 / 距離 / 賽道 / 場數建立檔位偏差表，之後再加入即日更新。",
        "model_risk": "高：香港賽馬檔位偏差足以令好馬變差價。",
        "validation_gate": "分檔位位置 ROI 及排名校準必須樣本外改善。",
    },
    7: {
        "name": "負磅及讓磅",
        "data_sources": ["參賽馬資料", "HKJC 排位表"],
        "current_support": "已把實際負磅作為數值特徵。",
        "gaps": "見習騎師減磅、負磅變化、馬匹體重及磅數轉馬位仍未建模。",
        "next_steps": "當 parser 支援後加入上仗負磅變化及減磅欄位。",
        "model_risk": "中：負磅要按班次及距離標準化先有實用價值。",
        "validation_gate": "負磅變化分桶校準改善後先可提升權重。",
    },
    8: {
        "name": "騎師因素",
        "data_sources": ["參賽馬資料", "賽果資料", "HKJC 排位表 / 賽果"],
        "current_support": "已從已匯入賽果計算騎師歷史勝率。",
        "gaps": "近期手風、場地專長、練馬師配合及人馬熟悉度仍未加入。",
        "next_steps": "加入滾動騎師狀態、騎練配合及騎師與馬匹配合特徵。",
        "model_risk": "中：換騎師經常解釋市場資金變化。",
        "validation_gate": "換騎師分片要改善，並避免小樣本過擬合。",
    },
    9: {
        "name": "練馬師因素",
        "data_sources": ["參賽馬資料", "賽果資料", "HKJC 排位表 / 賽果"],
        "current_support": "已從已匯入賽果計算練馬師歷史勝率。",
        "gaps": "近期馬房狀態、部署意圖、轉倉及班次部署仍缺失。",
        "next_steps": "加入滾動馬房狀態、降班 / 升班部署及轉倉改善特徵。",
        "model_risk": "中：馬房狀態及部署意圖會影響臨場投注判斷。",
        "validation_gate": "練馬師分片 walk-forward 指標需在最低樣本保護下改善。",
    },
    10: {
        "name": "馬主 / 馬房意圖",
        "data_sources": ["HKJC 報名資料", "馬主 / 馬房消息", "騎師配搭"],
        "current_support": "暫時未有專用意圖模型。",
        "gaps": "馬主模式、目標賽事、馬房信心及配搭訊號需要外部或衍生數據。",
        "next_steps": "先用班次部署及騎師配搭強度做衍生訊號，再考慮新聞來源。",
        "model_risk": "中：意圖可分辨熱身馬同搏殺馬。",
        "validation_gate": "只在 walk-forward 打贏 baseline 並提升 no-bet 精準度時推廣。",
    },
    11: {
        "name": "晨操及試閘",
        "data_sources": ["操練資料", "HKJC 晨操 / 試閘"],
        "current_support": "操練分數使用操練類型、時間、距離及名次。",
        "gaps": "視覺質素、試閘對手強度、時間衰減及操練文字解析仍較基本。",
        "next_steps": "加入時間衰減試閘 / 晨操特徵，並分開試閘與晨課訊號。",
        "model_risk": "中：有狀態訊號，但未驗證前噪音高。",
        "validation_gate": "狀態分片三甲命中率及 Brier 需改善。",
    },
    12: {
        "name": "配備變化",
        "data_sources": ["參賽馬資料", "HKJC 排位表"],
        "current_support": "已從參賽馬資料儲存配備欄位。",
        "gaps": "未轉成首次使用、除去、重戴等模型特徵。",
        "next_steps": "建立配備變化歷史特徵，按班次 / 距離測試首次配備效果。",
        "model_risk": "中：配備變動可能高訊號，但樣本細。",
        "validation_gate": "使用於注碼前必須通過特徵消融及 walk-forward 改善。",
    },
    13: {
        "name": "步速形態",
        "data_sources": ["參賽馬資料"],
        "current_support": "已用跑法建立基本領放 / 前置 / 後上壓力。",
        "gaps": "跑法經常未知，未有用分段或歷史位置推導 pace map。",
        "next_steps": "由歷史位置 / 分段推斷跑法，建立全場步速壓力分。",
        "model_risk": "高：步速錯判係組合玩法主要錯誤來源。",
        "validation_gate": "加入後錯誤分類中 pace 相關失誤應在樣本外下降。",
    },
    14: {
        "name": "賽事強度",
        "data_sources": ["賽事資料", "參賽馬資料", "賽果資料"],
        "current_support": "模型透過 pairwise ranking 隱含比較同場馬匹。",
        "gaps": "未有明確班次深度、對手質素、整體場次強度及步速組成特徵。",
        "next_steps": "由馬匹評分、近期速度及班次歷史建立場次強度聚合特徵。",
        "model_risk": "中：賽事強度決定歷史數據能否轉移到今場。",
        "validation_gate": "班次 / 場次強度分片必須樣本外改善。",
    },
    15: {
        "name": "賽前賠率",
        "data_sources": ["賠率資料", "HKJC GraphQL", "HKJC MQTT", "HKJC 最終賠率"],
        "current_support": "已儲存及顯示最新獨贏 / 位置賠率，並用作市場隱含概率及期望值。",
        "gaps": "仍要用最終賠率走勢校準不同下注時點。",
        "next_steps": "保持現有支援；下一步集中做臨場資金流及執行滑價。",
        "model_risk": "高：市場概率係模型最主要要打贏的 baseline。",
        "validation_gate": "任何賽馬特徵模型都要打贏市場-only walk-forward 先可推廣。",
    },
    16: {
        "name": "臨場賠率變化",
        "data_sources": ["賠率 ticks", "HKJC GraphQL / MQTT"],
        "current_support": "已把即時賠率 ticks 轉成最後 5 分鐘、2 分鐘、30 秒資金流及升溫 / 漂賠特徵。",
        "gaps": "需要更多真實賽日 ticks 及開跑時間錨點先算完整。",
        "next_steps": "累積即時 ticks；只有 Baseline 樣本外打贏 No Late Flow 先推廣。",
        "model_risk": "極高：臨場資金大機會係 ROI 主要盲點。",
        "validation_gate": "注碼使用前，樣本外 log loss、Brier 及 ROI 必須勝過 No Late Flow。",
    },
    17: {
        "name": "賽果及分段",
        "data_sources": ["賽果資料", "HKJC 賽果"],
        "current_support": "可儲存名次、完成時間、負距、400m / 800m 分段及評語。",
        "gaps": "分段及沿途際遇評語未完整轉成速度 / 受阻特徵。",
        "next_steps": "由歷史賽果建立校正速度分及沿途際遇標籤。",
        "model_risk": "高：只看名次會錯過不利際遇及隱藏升級馬。",
        "validation_gate": "速度 / 際遇特徵必須有 walk-forward 及錯誤分類證據。",
    },
    18: {
        "name": "即日賽道偏差",
        "data_sources": ["賽果資料", "參賽馬資料", "賠率 ticks", "賽事狀態"],
        "current_support": "即日偏差引擎會用同日同場同賽道已完賽場次建立內外檔及步速偏差。",
        "gaps": "需要更多賽日 replay 樣本、欄位資料及更準確前置 / 後上分類。",
        "next_steps": "逐場重播每個賽日；只有 Baseline 打贏 No Track Bias 且無未來資料洩漏才推廣。",
        "model_risk": "極高：即日偏差可直接反轉後段場次 edge。",
        "validation_gate": "按賽日順序回測；後場資料不可進入當前場次特徵。",
    },
    19: {
        "name": "天氣及環境",
        "data_sources": ["香港天文台 API", "賽事資料"],
        "current_support": "可按賽日及場地抓取 / 顯示天氣。",
        "gaps": "氣溫、濕度、雨量、風速及場地惡化仍未成為模型特徵。",
        "next_steps": "儲存天氣快照，加入場地惡化特徵並加資料洩漏保護。",
        "model_risk": "中：雨天或場地快速變化時影響最大。",
        "validation_gate": "天氣賽日分片必須改善後才可用於注碼。",
    },
    20: {
        "name": "歷史回測",
        "data_sources": ["賽果資料", "賠率 ticks", "模型預測"],
        "current_support": "已實作正期望獨贏 / 位置回測及 walk-forward 版本比較。",
        "gaps": "分彩池 ROI、分片 ROI 及最大回撤分析仍有限。",
        "next_steps": "加入彩池 / 馬場 / 距離 / 班次 ROI 分片及回撤控制。",
        "model_risk": "極高：任何方程式改動都必須通過此關。",
        "validation_gate": "所有升級都維持 mandatory walk-forward / out-of-sample gate。",
    },
    21: {
        "name": "模型解釋及校準",
        "data_sources": ["模型預測", "賽果資料"],
        "current_support": "已提供特徵貢獻解釋、Brier、log loss 及可靠度分桶。",
        "gaps": "仍未有嚴格自動升級 gate；錯誤分類仍需更完整持久化。",
        "next_steps": "加入持久校準歷史，未過 gate 時禁止模型升級。",
        "model_risk": "極高：未校準概率會破壞 Kelly 及組合 EV。",
        "validation_gate": "Brier / log loss / reliability curve 必須於樣本外改善。",
    },
    22: {
        "name": "彩池抽水及市場效率",
        "data_sources": ["HKJC 彩池規則", "官方抽水率"],
        "current_support": "已加入彩池派彩率、抽水率、最低投注單位、市場效率 buffer 及扣成本後 EV gate。",
        "gaps": "仍要定期覆核官方規則，並用真實賽事按彩池重播驗證 sensitivity / ROI。",
        "next_steps": "加入分彩池 replay，未過扣成本 EV、edge 及所需派彩門檻時自動不下注。",
        "model_risk": "極高：模型正 EV 可能被抽水完全吃掉。",
        "validation_gate": "以分彩池成本假設及敏感度區間重跑回測。",
    },
    23: {
        "name": "彩池選擇",
        "data_sources": ["模型預測", "投注決策"],
        "current_support": "已根據同一模型觀點產生獨贏 / 位置及組合候選。",
        "gaps": "缺少官方 / 可能組合派彩時，仍未能真正跨彩池按 EV 排序。",
        "next_steps": "接好 probable dividend 後，按真實 EV 排列所有彩池或選擇不下注。",
        "model_risk": "極高：同一觀點要放入最佳彩池，否則應放棄。",
        "validation_gate": "彩池選擇 replay ROI 必須勝過獨贏 / 位置 baseline。",
    },
    24: {
        "name": "組合派彩預測",
        "data_sources": ["HKJC 可能派彩", "HKJC MQTT recovery topics", "最終派彩", "彩池大小"],
        "current_support": "可儲存可能 / 最終 / 估算派彩，並將 QIN/QPL/FCT/TRIO/TCE/FIRST4/QUARTET 接入 EV 票。",
        "gaps": "彩池深度、最終組合派彩自動結算及分彩池校準仍未完成。",
        "next_steps": "真實賽日驗證 live feed，再加入最終派彩結算及分彩池 EV 校準。",
        "model_risk": "極高：無派彩就不能用組合玩法做注碼。",
        "validation_gate": "任何真實推薦前必須按彩池驗證 EV 校準。",
    },
    25: {
        "name": "相關曝險",
        "data_sources": ["投注候選", "資金設定"],
        "current_support": "已有單注及單場上限。",
        "gaps": "尚未因同一匹膽馬 / 腳位跨組合彩池而做相關性減注。",
        "next_steps": "建立馬匹及組合腳位曝險圖，降低高度相關票注碼。",
        "model_risk": "高：重複押同一觀點會不知不覺過度下注。",
        "validation_gate": "用 bankroll replay 比較開關相關曝險後的最大回撤。",
    },
    26: {
        "name": "不下注紀律",
        "data_sources": ["投注決策", "賽事生命週期"],
        "current_support": "已跳過弱 EV、弱 edge、已開跑及已完賽賽事。",
        "gaps": "仍可加入賽事層面信心及噪音 gate。",
        "next_steps": "根據校準不確定性及資料質素加入 race-level no-bet 規則。",
        "model_risk": "高：識得唔下注係 ROI 的一部分。",
        "validation_gate": "no-bet 規則必須改善 ROI / 回撤，且不能以資料洩漏隱藏虧損。",
    },
    27: {
        "name": "概率校準優先",
        "data_sources": ["賽果資料", "模型預測"],
        "current_support": "已有 Brier、log loss 及校準分桶。",
        "gaps": "校準仍主要係診斷，未成為硬性升級 / 注碼 gate。",
        "next_steps": "建立校準 gate，可靠度分桶不穩時自動降低注碼。",
        "model_risk": "極高：概率失準會令 Kelly 注碼失效。",
        "validation_gate": "提升曝險前必須改善 reliability-bin。",
    },
    28: {
        "name": "Walk-forward 升級門檻",
        "data_sources": ["賽果資料", "walk-forward 版本"],
        "current_support": "版本中心及 model_registry_runs 已比較模型版本並標示升級 gate。",
        "gaps": "仍未有自動替換 model JSON 工作流；CLV 樣本未足前只作監控。",
        "next_steps": "加入 promote 指令，registry、校準、回撤及 CLV 未過關就拒絕替換模型。",
        "model_risk": "極高：防止亂改權重或 UI 迭代污染方程式。",
        "validation_gate": "以 log loss、Brier、命中率、ROI、回撤及最低樣本數 gate。",
    },
    29: {
        "name": "錯誤分類資料庫",
        "data_sources": ["賽果資料", "模型預測", "賽事診斷"],
        "current_support": "已有 race_error_reviews 及 /api/error-taxonomy 分類首選與正 EV 失誤。",
        "gaps": "規則仍偏 heuristic，需要更豐富受阻評語、分段、亮相圈輸入及更大 replay 樣本。",
        "next_steps": "用錯誤分類數量決定下一個特徵實驗，並要求分類層面樣本外改善。",
        "model_risk": "高：無錯因分類，自我進化會失明。",
        "validation_gate": "針對修正後，相關錯誤類別在樣本外 replay 應下降；不能只靠人工分類升級。",
    },
    30: {
        "name": "臨場亮相 / 視覺狀態",
        "data_sources": ["亮相圈影片", "人工筆記", "視覺狀態來源"],
        "current_support": "暫時未有亮相圈輸入通道。",
        "gaps": "出汗、步姿、情緒、亮相及入閘行為需要視覺或人工資料。",
        "next_steps": "先加入人工結構化輸入；只有合規資料可用時才做自動視覺。",
        "model_risk": "中：臨場有用，但主觀噪音風險高。",
        "validation_gate": "只用有時間戳的賽前筆記做樣本外 replay 驗證。",
    },
    31: {
        "name": "落注滑價",
        "data_sources": ["賠率 ticks", "投注建議", "最終賠率"],
        "current_support": "betting_recommendations 已儲存建議賠率並可按最終賠率 / 賽果對數。",
        "gaps": "缺少實際落注確認及組合彩池滑價。",
        "next_steps": "加入落注時確認，接好官方 / 可能派彩後擴展 ledger 到組合彩池。",
        "model_risk": "高：賠率移動可在建議後吃走 edge。",
        "validation_gate": "用建議時、落注時及最終賠率 replay，報告滑價後 ROI。",
    },
    32: {
        "name": "多目標優化",
        "data_sources": ["回測", "walk-forward", "投注風險"],
        "current_support": "目前報告已有命中率、ROI、Brier / log loss 及風險上限。",
        "gaps": "未有同時優化 ROI、命中率、回撤、波動、校準及分彩池表現的統一 optimizer。",
        "next_steps": "加入升級 scorecard，納入回撤 / 波動及分彩池目標。",
        "model_risk": "高：只優化單一指標可能傷害資金生存率。",
        "validation_gate": "升級必須通過所有主要 gate，且不可明顯惡化回撤。",
    },
}


def database_snapshot(conn: sqlite3.Connection) -> dict[str, int]:
    tables = [
        "races",
        "runners",
        "results",
        "workouts",
        "odds_ticks",
        "raw_snapshots",
        "race_status",
        "model_registry_runs",
        "betting_recommendations",
        "exotic_dividends",
    ]
    snapshot: dict[str, int] = {}
    for table in tables:
        try:
            snapshot[table] = int(fetch_all(conn, f"SELECT count(*) AS n FROM {table}")[0]["n"])
        except sqlite3.Error:
            snapshot[table] = 0
    return snapshot


def coverage_items() -> list[dict[str, Any]]:
    return [
        item(
            1,
            "core",
            "Horse baseline ability",
            STATUS_PARTIAL,
            ["runners.csv", "results.csv", "HKJC racecard/results"],
            ["src/racing_model/features.py", "src/racing_model/storage.py", "data/sample/runners.csv"],
            "Uses official rating, carried weight, age, sex, recent speed/form and historical results.",
            "Class history, raw speed figures, horse-level long-term ability curves and stable changes are still shallow.",
            "Build normalized speed/ability ratings by track, distance, class and date; test against baseline with walk-forward log loss and ROI.",
            "High: weak baseline ability leaks into every pool probability.",
            "Out-of-sample log loss, Brier score, top-pick hit rate and value ROI must improve.",
            2,
        ),
        item(
            2,
            "core",
            "Recent condition",
            STATUS_PARTIAL,
            ["results.csv", "workouts.csv", "HKJC trackwork/results"],
            ["src/racing_model/features.py", "data/sample/workouts.csv"],
            "Uses recent finish position, recent speed and workout score.",
            "Layoff pattern, second-up/third-up profile, improvement/regression trajectory and vet flags are absent.",
            "Add recency buckets, days-since-run, form-cycle slope and layoff penalties; validate by race-date walk-forward.",
            "High: condition errors create false positives on stale ratings.",
            "Require improved calibration for recent-return runners and no ROI drawdown increase.",
            3,
        ),
        item(
            3,
            "core",
            "Distance suitability",
            STATUS_PARTIAL,
            ["races.csv", "results.csv"],
            ["src/racing_model/features.py"],
            "distance_fit scores past finishes by similarity to today's distance.",
            "Stretch-out/cut-back effects, sprint/mile/staying buckets and distance-by-pace interaction are not modeled.",
            "Add distance bucket records and distance-change features; compare per-distance ROI slices.",
            "Medium: distance misfit mostly hurts rank confidence and exotic tickets.",
            "Distance-sliced Brier and top-3 hit rate must improve out of sample.",
            4,
        ),
        item(
            4,
            "core",
            "Going and surface suitability",
            STATUS_PARTIAL,
            ["races.csv", "results.csv", "HKJC racecard/results"],
            ["src/racing_model/features.py", "src/racing_model/scrapers/hkjc.py"],
            "going_fit normalizes firm/good/soft/wet from historical finishes.",
            "All-weather/turf split, deterioration during the card and fine-grained going changes are incomplete.",
            "Separate surface and going histories; include same-day deterioration once race results arrive.",
            "Medium: wet/all-weather days can invalidate normal ratings.",
            "Going/surface slices must improve without hurting aggregate calibration.",
            5,
        ),
        item(
            5,
            "core",
            "Track and course",
            STATUS_PARTIAL,
            ["races.csv", "HKJC racecard"],
            ["src/racing_model/storage.py", "src/racing_model/features.py"],
            "Race rows store track and course, and the UI/localization can display Sha Tin/Happy Valley.",
            "Track/course are stored but not explicitly encoded as model features.",
            "Add track/course one-hot or target-encoded features with strict walk-forward folds.",
            "Medium: course layout affects draw, pace and distance suitability.",
            "Course-specific log loss and ROI must beat baseline/no-market variants.",
            6,
        ),
        item(
            6,
            "core",
            "Draw effect",
            STATUS_PARTIAL,
            ["runners.csv", "races.csv", "results.csv"],
            ["src/racing_model/features.py"],
            "Uses inside/outside draw flags based on field size.",
            "No draw bias by track, distance, rail position, course or same-day bias.",
            "Build draw-bias tables by track/distance/course/field size and add same-day updates later.",
            "High: HK draw bias can turn good horses into bad prices.",
            "Draw-sliced place ROI and rank calibration must improve out of sample.",
            2,
        ),
        item(
            7,
            "core",
            "Weight and claim",
            STATUS_PARTIAL,
            ["runners.csv", "HKJC racecard"],
            ["src/racing_model/features.py", "src/racing_model/scrapers/hkjc.py"],
            "Uses carried weight as a numeric feature.",
            "Apprentice claim, weight changes, horse body weight and weight-to-length conversion are not modeled.",
            "Add last-start weight deltas and claim fields when parser support is available.",
            "Medium: weight is useful only when normalized by class/distance.",
            "Weight-change buckets must show better calibration before promotion.",
            7,
        ),
        item(
            8,
            "core",
            "Jockey factor",
            STATUS_PARTIAL,
            ["runners.csv", "results.csv", "HKJC racecard/results"],
            ["src/racing_model/features.py"],
            "Uses historical jockey win rate from imported results.",
            "Recent form, course specialization, trainer pairing and horse familiarity are missing.",
            "Add rolling jockey form and jockey-trainer/horse pairing features.",
            "Medium: jockey changes often explain market moves.",
            "Promotion needs improved jockey-change slice and no overfit on small samples.",
            7,
        ),
        item(
            9,
            "core",
            "Trainer factor",
            STATUS_PARTIAL,
            ["runners.csv", "results.csv", "HKJC racecard/results"],
            ["src/racing_model/features.py"],
            "Uses historical trainer win rate from imported results.",
            "Recent stable form, placement intent, stable transfer and class targeting are missing.",
            "Add rolling trainer form and class/drop-up placement features.",
            "Medium: stable form and intent influence live betting decisions.",
            "Trainer-sliced walk-forward metrics must improve with minimum sample guard.",
            7,
        ),
        item(
            10,
            "core",
            "Owner/stable intent",
            STATUS_EXTERNAL,
            ["HKJC entries", "ownership/stable news", "jockey bookings"],
            [],
            "No dedicated intent model yet.",
            "Owner patterns, target races, stable confidence and booking signals need external or derived data.",
            "Start with derived class placement and booking-strength signals before adding news feeds.",
            "Medium: intent can separate fit horses from target horses.",
            "Only promote if intent features beat baseline in walk-forward and improve no-bet precision.",
            8,
        ),
        item(
            11,
            "core",
            "Trackwork and trials",
            STATUS_PARTIAL,
            ["workouts.csv", "HKJC trackwork/trials"],
            ["src/racing_model/features.py", "src/racing_model/scrapers/hkjc.py", "data/sample/workouts.csv"],
            "workout_score uses work type, time, distance and rank.",
            "Visual quality, trial strength, recency decay and trackwork text parsing remain basic.",
            "Add recency-decayed trial/workout features and separate trial from morning work.",
            "Medium: useful condition signal, but noisy without validation.",
            "Condition-sliced top-3 hit rate and Brier score must improve.",
            6,
        ),
        item(
            12,
            "core",
            "Gear changes",
            STATUS_PARTIAL,
            ["runners.csv", "HKJC racecard"],
            ["src/racing_model/storage.py", "src/racing_model/scrapers/hkjc.py"],
            "Gear is stored from runner data.",
            "Gear is not converted into first-time/removed/reapplied model features.",
            "Create gear-change history features and test first-time gear by class/distance.",
            "Medium: gear changes can be high signal but sample sizes are small.",
            "Require feature ablation and walk-forward improvement before using in stake sizing.",
            6,
        ),
        item(
            13,
            "core",
            "Pace shape",
            STATUS_PARTIAL,
            ["runners.csv"],
            ["src/racing_model/features.py"],
            "Basic leader/pace/closer pressure from running_style.",
            "Running styles are often unknown; no sectional-derived pace map or race-flow simulation.",
            "Infer running style from historical positions/sectionals and build race-level pressure score.",
            "High: pace errors are a core loss category for exotics.",
            "Pace-tagged losing decisions should reduce in the error taxonomy once added.",
            3,
        ),
        item(
            14,
            "core",
            "Race strength",
            STATUS_PARTIAL,
            ["races.csv", "runners.csv", "results.csv"],
            ["src/racing_model/features.py", "src/racing_model/model.py"],
            "Model implicitly compares runners in a race through pairwise ranking.",
            "No explicit class depth, opponent quality, field quality or pace-mix strength feature.",
            "Add field-strength aggregates from runner ratings, recent speed and class history.",
            "Medium: race strength controls whether historical figures transfer.",
            "Class/field-strength slices must improve out of sample.",
            7,
        ),
        item(
            15,
            "core",
            "Pre-race odds",
            STATUS_DONE,
            ["odds.csv", "HKJC GraphQL", "HKJC MQTT", "HKJC results final odds"],
            ["src/racing_model/odds.py", "src/racing_model/storage.py", "src/racing_model/features.py"],
            "Latest win/place odds are stored, exposed and used for market-implied probability and EV.",
            "Needs calibration against final odds movement for pre-race timing decisions.",
            "Keep current support; next work belongs to late money-flow windows and execution slippage.",
            "High: market probability is the model's main baseline to beat.",
            "No model using racing features should be promoted unless it beats market-only walk-forward.",
            1,
        ),
        item(
            16,
            "core",
            "Late odds movement",
            STATUS_PARTIAL,
            ["odds_ticks", "HKJC GraphQL/MQTT"],
            [
                "src/racing_model/odds.py",
                "src/racing_model/live.py",
                "src/racing_model/storage.py",
                "src/racing_model/features.py",
                "src/racing_model/walk_forward.py",
            ],
            "Time-stamped live odds are converted into final 5 min, 2 min and 30 sec movement, plus steam/drift features.",
            "Needs more live race-day ticks and post-time anchoring before it can be considered fully complete.",
            "Accumulate live ticks, then promote late-flow only if Baseline beats No Late Flow out of sample.",
            "Very high: late money is likely a major ROI blind spot.",
            "Baseline must beat No Late Flow on out-of-sample log loss, Brier and ROI before stake sizing uses it.",
            1,
        ),
        item(
            17,
            "core",
            "Results and sectionals",
            STATUS_PARTIAL,
            ["results.csv", "HKJC results"],
            ["src/racing_model/storage.py", "src/racing_model/scrapers/hkjc.py"],
            "Stores finish position, time, margin, 400m/800m sectionals and comments when available.",
            "Sectionals and trip comments are not fully converted into speed/trip features.",
            "Create adjusted speed figures and trip-note tags from result history.",
            "High: raw finish position misses unlucky runs and hidden upgrades.",
            "Speed/trip features need walk-forward and error-taxonomy proof.",
            3,
        ),
        item(
            18,
            "core",
            "Same-day track bias",
            STATUS_PARTIAL,
            ["results.csv", "runners.csv", "odds_ticks", "race_status"],
            [
                "src/racing_model/track_bias.py",
                "src/racing_model/features.py",
                "src/racing_model/walk_forward.py",
            ],
            "Same-day bias engine uses earlier resulted races on the same date, track and course to build inside/outside and pace-bias features.",
            "Needs larger race-day replay samples, rail-position detail and stronger front/closer classification before full stake sizing.",
            "Replay each race day sequentially and promote only if Baseline beats No Track Bias without future-race leakage.",
            "Very high: same-day bias can flip later-race model edges.",
            "Backtest by replaying race-day sequence; no later race on the same day may enter the current race features.",
            1,
        ),
        item(
            19,
            "core",
            "Weather and environment",
            STATUS_PARTIAL,
            ["Hong Kong Observatory API", "races.csv"],
            ["src/racing_model/weather.py", "src/racing_model/web/app.js"],
            "Weather is fetched/displayed for race day and venue.",
            "Temperature, humidity, rain, wind and track deterioration are not model features.",
            "Persist weather snapshots and add going-deterioration features with leakage guards.",
            "Medium: matters most on rain or changing-track days.",
            "Weather-day slices must improve before stake sizing uses it.",
            8,
        ),
        item(
            20,
            "core",
            "Historical backtesting",
            STATUS_DONE,
            ["results.csv", "odds_ticks", "model predictions"],
            ["src/racing_model/backtest.py", "src/racing_model/walk_forward.py", "src/racing_model/evolution.py"],
            "Positive-EV win/place backtest and walk-forward version comparison are implemented.",
            "Pool-specific ROI slices and drawdown analysis are still limited.",
            "Add pool/track/distance/class ROI slices and drawdown controls.",
            "Very high: every equation change must clear this gate.",
            "Keep mandatory walk-forward / out-of-sample gates for promotion.",
            1,
        ),
        item(
            21,
            "core",
            "Model explainability and calibration",
            STATUS_PARTIAL,
            ["model predictions", "results.csv"],
            ["src/racing_model/model.py", "src/racing_model/evolution.py", "src/racing_model/web/app.js"],
            "Feature contribution explanation, Brier score, log loss and reliability bins are available.",
            "No persistent error taxonomy and no strict automated promotion gate yet.",
            "Add persistent calibration history and block model promotion unless gates pass.",
            "Very high: uncalibrated probabilities break Kelly and exotic EV.",
            "Brier/log loss/reliability curve must improve on out-of-sample folds.",
            1,
        ),
        item(
            22,
            "blind_spot",
            "Pool takeout and market efficiency",
            STATUS_PARTIAL,
            ["HKJC pool rules", "official takeout"],
            ["src/racing_model/pool_rules.py", "src/racing_model/betting.py", "src/racing_model/web/app.js"],
            "Pool payout rates, takeout rates, minimum units, market-efficiency buffers and cost-adjusted EV gates are implemented.",
            "Rates still need periodic official review, sensitivity backtests, and real-race validation by pool.",
            "Run pool-specific replay and reject stakes when cost-adjusted EV or edge gates fail.",
            "Very high: positive model EV can disappear after takeout.",
            "Backtest with pool-specific cost assumptions and sensitivity bands.",
            2,
        ),
        item(
            23,
            "blind_spot",
            "Pool selection",
            STATUS_PARTIAL,
            ["predictions", "betting decisions"],
            ["src/racing_model/betting.py", "src/racing_model/web/app.js"],
            "WIN/PLACE decisions and exotic candidates are generated from the same model opinion.",
            "Official/probable exotic dividends are absent, so selection is not true EV-ranked across pools.",
            "Rank all pools by real EV after probable-dividend support lands.",
            "Very high: same opinion must be placed in the best pool or skipped.",
            "Pool-choice replay must improve ROI versus WIN/PLACE-only baseline.",
            2,
        ),
        item(
            24,
            "blind_spot",
            "Exotic dividend prediction",
            STATUS_PARTIAL,
            ["HKJC GraphQL probable dividends", "HKJC MQTT recovery topics", "final dividends", "pool size/tote data"],
            [
                "src/racing_model/betting.py",
                "src/racing_model/exotic_dividends.py",
                "src/racing_model/exotic_live.py",
                "src/racing_model/storage.py",
            ],
            "exotic_dividends can store probable/final/estimated dividends; live GraphQL/MQTT providers refresh QIN/QPL/FCT/TRIO/TCE/FIRST4/QUARTET into EV tickets.",
            "Pool-size/tote depth, final exotic dividend auto-settlement and per-pool calibration are still incomplete.",
            "Validate live-feed availability on real race days, then add final dividend settlement and per-pool EV calibration.",
            "Very high: exotics are unusable for stake sizing without dividends.",
            "Validate EV calibration by pool before any real recommendations.",
            1,
        ),
        item(
            25,
            "blind_spot",
            "Correlated exposure",
            STATUS_PARTIAL,
            ["betting candidates", "bankroll settings"],
            ["src/racing_model/betting.py"],
            "Per-bet and per-race caps exist.",
            "No correlation-aware reduction for shared banker/legs across exotic pools.",
            "Add exposure graph by horse and combination legs; reduce stake on correlated tickets.",
            "High: duplicated opinions can silently overbet one horse.",
            "Replay bankroll drawdown with correlated tickets enabled versus disabled.",
            2,
        ),
        item(
            26,
            "blind_spot",
            "No-bet discipline",
            STATUS_DONE,
            ["betting decisions", "race lifecycle"],
            ["src/racing_model/betting.py", "src/racing_model/web/app.js"],
            "Eligibility gates skip weak EV, weak edge, live races and resulted races.",
            "Could still use race-level confidence/noise gates.",
            "Add race-level no-bet rules from calibration uncertainty and data quality.",
            "High: skipping weak races is part of ROI.",
            "No-bet rules must improve ROI/drawdown without hiding losses via leakage.",
            2,
        ),
        item(
            27,
            "blind_spot",
            "Probability calibration first",
            STATUS_PARTIAL,
            ["results.csv", "predictions"],
            ["src/racing_model/evolution.py", "src/racing_model/walk_forward.py"],
            "Brier score, log loss and calibration bins exist.",
            "Calibration is diagnostic, not yet a hard promotion/stake gate.",
            "Create calibration gate and reduce stakes when reliability bins are unstable.",
            "Very high: Kelly staking fails with miscalibrated probabilities.",
            "Require reliability-bin improvement before increasing exposure.",
            1,
        ),
        item(
            28,
            "blind_spot",
            "Walk-forward promotion gates",
            STATUS_PARTIAL,
            ["results.csv", "walk-forward variants"],
            ["src/racing_model/walk_forward.py", "src/racing_model/evolution.py", "src/racing_model/model_registry.py"],
            "Walk-forward version center and persistent model_registry_runs compare variants and label promotion gate status.",
            "No automated model JSON replacement workflow yet, and CLV is still only monitored until enough live ledger samples exist.",
            "Add explicit promote command that refuses model replacement unless registry, calibration, drawdown and CLV gates pass.",
            "Very high: prevents random weight/UI iteration from corrupting the equation.",
            "Gate on log loss, Brier, hit rate, ROI and drawdown with minimum sample sizes.",
            1,
        ),
        item(
            29,
            "blind_spot",
            "Error taxonomy",
            STATUS_PARTIAL,
            ["results.csv", "predictions", "race diagnostics"],
            [
                "src/racing_model/error_taxonomy.py",
                "src/racing_model/storage.py",
                "src/racing_model/evolution.py",
                "src/racing_model/web/app.js",
            ],
            "Persistent race_error_reviews table and /api/error-taxonomy classify top-pick and positive-EV losses.",
            "Rules are still heuristic and need richer trip notes, sectionals, paddock input and larger replay samples.",
            "Use taxonomy counts to target the next feature experiment, then require category-specific out-of-sample improvement.",
            "High: without error causes, the self-improving loop is blind.",
            "Error category counts must fall in out-of-sample replay after targeted fixes; no manual promotion from taxonomy alone.",
            3,
        ),
        item(
            30,
            "blind_spot",
            "Live paddock/visual condition",
            STATUS_EXTERNAL,
            ["paddock video", "manual notes", "visual condition feed"],
            [],
            "No paddock input path.",
            "Sweat, gait, temperament, parade and gate behavior require visual/manual data.",
            "Add manual structured input first; only automate visuals if compliant data is available.",
            "Medium: useful near race time but high risk of subjective noise.",
            "Validate only with timestamped pre-race notes and out-of-sample replay.",
            9,
        ),
        item(
            31,
            "blind_spot",
            "Execution slippage",
            STATUS_PARTIAL,
            ["odds_ticks", "recommended tickets", "final odds"],
            ["src/racing_model/betting_ledger.py", "src/racing_model/storage.py", "src/racing_model/web/app.js"],
            "betting_recommendations stores active WIN/PLACE recommendations with suggested odds and reconciles against final odds/results.",
            "Bet-time execution confirmation and exotic-pool slippage are still absent.",
            "Add explicit bet-time confirmation and extend ledger to exotic pools once official/probable dividends are available.",
            "High: tote movement can erase edge after the model recommends a bet.",
            "Replay decisions using bet-time odds and final odds; report slippage-adjusted ROI.",
            2,
        ),
        item(
            32,
            "blind_spot",
            "Multi-objective optimization",
            STATUS_PARTIAL,
            ["backtest", "walk-forward", "betting risk"],
            ["src/racing_model/backtest.py", "src/racing_model/walk_forward.py", "src/racing_model/betting.py"],
            "Current reports include hit rate, ROI, Brier/log loss and risk caps.",
            "No unified optimizer across ROI, hit rate, drawdown, volatility, calibration and pool performance.",
            "Add promotion scorecard with drawdown/volatility and pool-specific objectives.",
            "High: optimizing one metric can worsen bankroll survival.",
            "Promotion must pass all primary gates and avoid material drawdown deterioration.",
            4,
        ),
    ]


def item(
    item_id: int,
    category: str,
    name: str,
    status: str,
    data_sources: list[str],
    supported_files: list[str],
    current_support: str,
    gaps: str,
    next_steps: str,
    model_risk: str,
    validation_gate: str,
    priority: int,
) -> dict[str, Any]:
    return {
        "id": item_id,
        "category": category,
        "category_label": "21 個主分析項" if category == "core" else "額外盲點",
        "name": name,
        "status": status,
        "status_key": status_key(status),
        "data_sources": data_sources,
        "supported_files": supported_files,
        "current_support": current_support,
        "gaps": gaps,
        "next_steps": next_steps,
        "model_risk": model_risk,
        "validation_gate": validation_gate,
        "priority": priority,
    }


def status_key(status: str) -> str:
    return {
        STATUS_DONE: "done",
        STATUS_PARTIAL: "partial",
        STATUS_MISSING: "missing",
        STATUS_EXTERNAL: "external",
    }[status]
