from __future__ import annotations

import sqlite3
from typing import Any

from .storage import fetch_all


STATUS_DONE = "已完成"
STATUS_PARTIAL = "部分完成"
STATUS_MISSING = "未完成"
STATUS_EXTERNAL = "需要外部數據"

STATUS_WEIGHTS = {
    STATUS_DONE: 1.0,
    STATUS_PARTIAL: 0.5,
    STATUS_EXTERNAL: 0.15,
    STATUS_MISSING: 0.0,
}

MATURITY_OVERRIDES = {
    14: (
        0.56,
        "已加入回填吞吐優化：歷史回填/賽日載入/補完 runners 可用獨立 backfill request delay，並避免對已有 `last_six_runs` 的馬重覆抓 horse profile；缺失時會先重用資料庫歷史值，再退回抓 profile 頁。仍未做到跨日並行抓取及更細緻來源節流。",
    ),
    24: (
        0.72,
        "已由純候選排序進展到官方派彩 gate、分池 replay gate、馬場/路程/班次情境切片、walk-forward pool-choice optimizer、ROI 封鎖/降注及 UI 可解釋狀態；仍未完成更長期分切片閾值訓練。",
    ),
    25: (
        0.62,
        "已接入 probable/final dividend 儲存、官方派彩 gate、final dividend audit、自動補抓對數、分池 replay stake gate 及情境切片校準；仍未有完整彩池深度和長期 final-dividend 校準。",
    ),
    30: (
        0.58,
        "已由離線可靠度分桶推進到即場同分熔斷：當能力/融合模型對全場輸出近乎完全平均概率時，會改用最新獨贏/位置市場公平機率計算概率及EV，並把 EV 標記為市場水位/抽水參考而非模型 edge，下注 gate 只會觀望；仍未完成組合彩池結構層校準。",
    ),
    35: (
        0.74,
        "已由純 scorecard gate 推前到 walk-forward 候選模型排序、model registry 升級 gate、彩池 optimizer 注碼調整、EV 黑箱日滾動微調及全賽日 final refit；可用歷史獨贏賠率按 +EV、平均概率/命中率、ROI、賽事覆蓋率及回撤搜尋模型與下注門檻，先用最近賽日 tuning 選 candidate，再用所有 eligible 賽事 fit 最終模型；仍未接入正式自動 promotion。",
    ),
    36: (
        0.62,
        "已由靜態 EV gate 推進到黑箱下注/不下注門檻搜尋：候選會按最低 EV、最低勝率、賠率上下限及每場最多下注數決定是否落飛，objective 已避免過度少票，容許每日較高覆蓋但要求 +EV、概率及 ROI 過關；仍未按彩池和賽事風險做完整分層 gate。",
    ),
}


def build_coverage_report(conn: sqlite3.Connection) -> dict[str, Any]:
    items = coverage_items()
    status_counts = {status: 0 for status in STATUS_WEIGHTS}
    for item_data in items:
        status_counts[str(item_data["status"])] += 1

    status_weighted = sum(STATUS_WEIGHTS[str(item_data["status"])] for item_data in items)
    weighted = sum(float(item_data.get("maturity_score", STATUS_WEIGHTS[str(item_data["status"])])) for item_data in items)
    max_score = len(items) or 1
    coverage_score = weighted / max_score
    coarse_status_score = status_weighted / max_score
    status_progress_score = (coverage_score + coarse_status_score) / 2.0
    blocked = [item_data for item_data in items if item_data["status"] in {STATUS_MISSING, STATUS_EXTERNAL}]
    priority_items = sorted(
        blocked,
        key=lambda item_data: (int(item_data["priority"]), int(item_data["id"])),
    )[:8]

    return {
        "title": "方程式覆蓋率 / 盲點報告",
        "objective": "以 36 個賽馬方程式主項追蹤模型補洞進度；所有補洞都要用 walk-forward / out-of-sample 證明提升。",
        "status_labels": {
            "done": STATUS_DONE,
            "partial": STATUS_PARTIAL,
            "missing": STATUS_MISSING,
            "external": STATUS_EXTERNAL,
        },
        "summary": {
            "target_groups": 36,
            "total_groups": len(items),
            "core_groups": sum(1 for item_data in items if item_data["category"] == "core"),
            "blind_spot_groups": sum(1 for item_data in items if item_data["category"] == "advanced"),
            "coverage_score": round(coverage_score, 4),
            "status_coverage_score": round(status_progress_score, 4),
            "coarse_status_score": round(coarse_status_score, 4),
            "coverage_score_method": "覆蓋分以每項 maturity_score 計算；狀態進度分會混合粗分類與 maturity，所以每次有實質模型補洞都會同步變動；粗分類基準只在已完成/部分完成等大狀態改變時變動。",
            "status_counts": status_counts,
            "database": database_snapshot(conn),
        },
        "items": items,
        "priority_next_steps": [
            {
                "id": item_data["id"],
                "name": item_data["name"],
                "status": item_data["status"],
                "model_risk": item_data["model_risk"],
                "next_steps": item_data["next_steps"],
                "validation_gate": item_data["validation_gate"],
            }
            for item_data in priority_items
        ],
    }


def database_snapshot(conn: sqlite3.Connection) -> dict[str, int]:
    tables = [
        "races",
        "runners",
        "results",
        "workouts",
        "odds_ticks",
        "raw_snapshots",
        "race_status",
        "model_registry_runs",
        "betting_recommendations",
        "exotic_dividends",
    ]
    snapshot: dict[str, int] = {}
    for table in tables:
        try:
            snapshot[table] = int(fetch_all(conn, f"SELECT count(*) AS n FROM {table}")[0]["n"])
        except sqlite3.Error:
            snapshot[table] = 0
    return snapshot


def coverage_items() -> list[dict[str, Any]]:
    rows = [
        spec(
            1,
            "core",
            "賽事基本條件",
            STATUS_PARTIAL,
            ["賽事資料", "HKJC 排位表", "賽果資料", "天氣資料"],
            ["src/racing_model/storage.py", "src/racing_model/features.py", "src/racing_model/weather.py"],
            "已儲存馬場、賽道、距離、場地狀態、班次、賽事狀態及部分天氣顯示。",
            "馬場幾何、欄位、坡度、獎金、日夜賽、溫濕度與即日場地變化仍未完整進入模型。",
            "把場地、跑道、距離、班次、獎金、賽事時間及天氣轉成分桶特徵，按馬場/距離做 walk-forward 分片。",
            ["馬場", "跑道類型", "場地狀態", "賽程距離", "賽事級別", "獎金", "參賽馬數", "賽事時間"],
            "高：基本條件係所有歷史表現能否轉移到今場的前提。",
            "分馬場、距離、場地狀態的 log loss / Brier / ROI 必須樣本外改善。",
            2,
        ),
        spec(
            2,
            "core",
            "馬匹本身能力",
            STATUS_PARTIAL,
            ["參賽馬資料", "賽果資料", "晨操/試閘", "獸醫資料"],
            ["src/racing_model/features.py", "src/racing_model/model.py", "src/racing_model/trip_diagnostics.py", "src/racing_model/pace_profile.py", "data/sample/runners.csv"],
            "已用官方評分、年齡、性別、近期速度、近績、負磅及同場 pairwise ranking 建立基礎能力。",
            "耐力、爆發力、穩定性、體重變化、健康紀錄、心理性格、起步、轉彎、換腳等仍未完整建模。",
            "建立標準化速度評分、馬匹能力曲線、體重/健康/跑法特徵，並用特徵消融驗證。",
            ["整體實力評分", "速度能力", "耐力", "爆發力", "穩定性", "年齡/性別", "體重", "健康", "心理性格", "跑法", "轉彎", "起步", "換腳平衡"],
            "極高：馬匹能力估錯會污染勝率、位置率及所有組合彩池。",
            "能力特徵必須打贏 market-only 與現有 baseline，並改善三甲校準。",
            1,
        ),
        spec(
            3,
            "core",
            "近期狀態",
            STATUS_PARTIAL,
            ["賽果資料", "晨操資料", "試閘資料", "獸醫報告"],
            ["src/racing_model/features.py", "src/racing_model/trip_diagnostics.py", "data/sample/workouts.csv"],
            "已使用近績、近期速度及操練分數。",
            "休息日數、狀態走勢、上仗不利解讀、試閘姿態、晨操強度及賽後恢復仍較淺。",
            "加入休息週期、狀態斜率、復出場次、上仗受阻/熱身標籤及獸醫旗標。",
            ["近績", "狀態走勢", "休息日數", "試閘/晨操", "上仗解讀", "賽後恢復"],
            "高：近期狀態錯判會令過時能力分變成假 value。",
            "復出馬、密跑馬及轉勢馬分片要在 out-of-sample 改善。",
            3,
        ),
        spec(
            4,
            "core",
            "騎師因素",
            STATUS_PARTIAL,
            ["參賽馬資料", "賽果資料", "HKJC 排位表/賽果"],
            ["src/racing_model/features.py"],
            "已用匯入賽果計算騎師歷史勝率，UI 顯示中文騎師名。",
            "人馬配合、馬場/距離適性、當日手風、決策能力及騎師動機仍未完整。",
            "加入滾動騎師狀態、騎師與馬匹配合、騎練組合、當日成績及換騎師訊號。",
            ["整體能力", "人馬配合", "馬場適性", "當日狀態", "決策能力", "騎師動機"],
            "中高：騎師變動經常與市場資金流及部署意圖有關。",
            "換騎師/騎練組合分片必須改善且有最低樣本數保護。",
            5,
        ),
        spec(
            5,
            "core",
            "練馬師因素",
            STATUS_PARTIAL,
            ["參賽馬資料", "賽果資料", "HKJC 排位表/賽果"],
            ["src/racing_model/features.py"],
            "已用匯入賽果計算練馬師歷史勝率，UI 顯示中文練馬師名。",
            "近期馬房狀態、部署模式、騎練組合、新馬/轉倉改善未完整。",
            "加入滾動馬房勝率、部署模式、升降班策略、轉倉及新馬特徵。",
            ["整體成績", "馬房狀態", "部署模式", "騎練組合", "新馬/轉倉馬"],
            "中高：馬房部署會直接影響是否搏殺。",
            "馬房狀態及部署特徵要在 walk-forward 提升 no-bet 精準度。",
            5,
        ),
        spec(
            6,
            "core",
            "負磅與讓磅",
            STATUS_PARTIAL,
            ["參賽馬資料", "HKJC 排位表"],
            ["src/racing_model/features.py", "src/racing_model/scrapers/hkjc.py", "src/racing_model/trip_diagnostics.py"],
            "已使用實際負磅作為數值特徵。",
            "上仗負磅變化、見習減磅、馬匹體重與負磅比例、距離/班次互動仍未完整。",
            "加入負磅變化、減磅欄位、體重比例及按距離/班次的磅數校正。",
            ["實際負磅", "讓磅優勢", "體重與負磅比例", "距離與負磅", "班次與負磅"],
            "中：未標準化的磅數容易被模型錯解。",
            "負磅分桶及距離互動要改善校準才可提升權重。",
            7,
        ),
        spec(
            7,
            "core",
            "排位與檔位",
            STATUS_PARTIAL,
            ["參賽馬資料", "賽事資料", "賽果資料"],
            ["src/racing_model/features.py", "src/racing_model/track_bias.py"],
            "已加入內檔/外檔旗標，並有即日偏差引擎的初步檔位訊號。",
            "未按馬場、距離、欄位、場地狀態、鄰近快馬及樣本大小建立完整檔位模型。",
            "建立馬場/距離/欄位/場地狀態的檔位偏差表，並加入跑法與鄰近馬互動。",
            ["檔位", "馬場檔位偏差", "跑法與檔位配合", "鄰近馬影響", "歷史檔位統計"],
            "高：香港賽事檔位足以改變排名及組合機率。",
            "分檔位 ROI、三甲命中及即日偏差 replay 必須改善。",
            2,
        ),
        spec(
            8,
            "core",
            "步速與賽事形態",
            STATUS_PARTIAL,
            ["參賽馬資料", "賽果分段", "沿途位置"],
            ["src/racing_model/features.py", "src/racing_model/track_bias.py", "src/racing_model/error_taxonomy.py", "src/racing_model/trip_diagnostics.py", "src/racing_model/pace_profile.py"],
            "已加入 pace profile v2：由近 6 場沿途位置拆起步速度、中段推進、轉彎位置、末段追勢、前領轉弱、塞車歷史及路程步速配合，並進入模型特徵。",
            "仍未有官方逐段時間、彎位橫移路徑及逐馬群交通 replay；早段樣本不足時仍需保守收縮。",
            "下一步用更多賽果分段驗證 pace projection 命中率，再加入 Monte Carlo 交通路徑。",
            ["早段步速", "領放壓力", "跑法分布", "賽事節奏", "位置預測", "受阻風險"],
            "極高：步速錯判係組合玩法同冷門錯判的主要來源。",
            "加入後 pace 類錯誤要在樣本外下降，且組合 ROI 不可惡化。",
            1,
        ),
        spec(
            9,
            "core",
            "血統因素",
            STATUS_PARTIAL,
            ["血統資料", "外地馬資料", "家族賽績"],
            ["src/racing_model/storage.py", "src/racing_model/scrapers/hkjc.py", "src/racing_model/features.py"],
            "已由 HKJC 排位表抽取父系/母系，並建立同父/同母馬相近路程、場地及新馬資料稀疏風險 proxy。",
            "仍未有外地賽績、完整兄弟姐妹關係、早熟/遲熟曲線及人工血統庫。",
            "加入外地馬轉場血統庫，並按新馬、初跑泥地、增程分片做 out-of-sample 驗證。",
            ["父系", "母系", "家族賽績", "新馬與轉程判斷"],
            "中：對新馬、外地馬、初跑泥地/增程特別重要。",
            "只在新馬/少賽績分片通過 out-of-sample 才可使用。",
            8,
        ),
        spec(
            10,
            "core",
            "配備與裝備",
            STATUS_PARTIAL,
            ["參賽馬資料", "HKJC 排位表"],
            ["src/racing_model/storage.py", "src/racing_model/scrapers/hkjc.py"],
            "已儲存配備欄位。",
            "首次戴、重戴、除去、多項配備同改及蹄鐵變化未轉成模型特徵。",
            "建立配備歷史與變動特徵，按配備類型、班次、距離做消融測試。",
            ["眼罩", "面箍/頭罩", "舌帶", "交叉鼻箍", "耳塞", "蹄鐵", "配備變動信號"],
            "中：高訊號但容易小樣本過擬合。",
            "配備特徵要通過 walk-forward 與小樣本收縮保護。",
            6,
        ),
        spec(
            11,
            "core",
            "班次與評分變化",
            STATUS_PARTIAL,
            ["賽事資料", "參賽馬資料", "賽果資料"],
            ["src/racing_model/features.py", "src/racing_model/model.py", "src/racing_model/trip_diagnostics.py", "src/racing_model/pace_profile.py"],
            "已使用官方評分、賽事班次、對手平均評分，並加入升降班訊號、評分變化及隱藏能力訊號。",
            "仍未完整追蹤評分調整原因、馬房搏殺部署及同班同程長期 par；隱藏能力暫以走位/對手/近績 heuristic 推斷。",
            "下一步把評分調整與賽後診斷連成實驗 backlog，驗證升降班/評分訊號對 log loss、ROI 及 no-bet gate 的增益。",
            ["升班", "降班", "評分升跌", "隱藏能力"],
            "高：評分與班次係香港讓賽核心。",
            "分班次 log loss、ROI、no-bet 準確度必須改善。",
            2,
        ),
        spec(
            12,
            "core",
            "賠率與市場資訊",
            STATUS_DONE,
            ["賠率 ticks", "HKJC GraphQL", "HKJC MQTT", "最終賠率"],
            ["src/racing_model/odds.py", "src/racing_model/live.py", "src/racing_model/market_flow.py", "src/racing_model/features.py"],
            "已儲存獨贏/位置 ticks，計算市場隱含概率、EV、價值差距及臨場資金流。",
            "成交量、真正大戶資金、公眾追熱識別及最終 CLV 樣本仍不足。",
            "累積真實賽日 ticks，分最後 5/2/0.5 分鐘驗證資金流與 CLV。",
            ["獨贏賠率", "位置賠率", "賠率異動", "成交量", "賠率價值", "水位與抽水", "熱門偏差"],
            "極高：市場係模型要打贏的主要 baseline。",
            "任何特徵模型都要打贏 market-only walk-forward。",
            1,
        ),
        spec(
            13,
            "core",
            "投注類型",
            STATUS_PARTIAL,
            ["模型預測", "組合派彩", "投注決策"],
            ["src/racing_model/betting.py", "src/racing_model/exotic_dividends.py", "src/racing_model/betting_ledger.py"],
            "已支援 WIN/PLACE 及 QIN/QPL/FCT/TRIO/TCE/FIRST4/QUARTET 候選與部分結算。",
            "多場投注、跨場相關性、排名分布校準及每個彩池的最終 ROI 尚未完整。",
            "完善組合彩池派彩、按池 replay、跨彩池/跨馬曝險及多場投注先暫不做。",
            ["獨贏", "位置", "連贏", "位置Q", "二重彩", "三連彩", "三重彩", "四連環/四重彩", "多場投注"],
            "極高：選錯彩池會把正確觀點變成負 EV。",
            "每個彩池都要有 hit rate、ROI、回撤及派彩校準。",
            2,
        ),
        spec(
            14,
            "core",
            "資料來源",
            STATUS_PARTIAL,
            ["HKJC 賽事/賽果", "賠率", "晨操", "天氣", "新聞/影片"],
            ["src/racing_model/scrapers/hkjc.py", "src/racing_model/storage.py", "src/racing_model/weather.py"],
            "已有 HKJC racecard/results/trackwork parser、odds providers、raw snapshot 及天氣顯示。",
            "影片、獸醫報告結構化、完整分段、新聞/馬房消息、成交量及場地即時資料仍不足。",
            "建立資料來源清單與品質分，缺資料時降低信心或不下注。",
            ["官方賽績", "分段時間", "賽事影片", "獸醫報告", "試閘", "晨操", "天氣", "即時場地", "賠率", "新聞馬房消息"],
            "極高：資料品質差會直接污染回測與實戰。",
            "所有新資料源要有 raw snapshot、parser test 及缺失值處理。",
            3,
        ),
        spec(
            15,
            "core",
            "資料清洗與特徵工程",
            STATUS_PARTIAL,
            ["賽果資料", "賠率 ticks", "特徵工程"],
            ["src/racing_model/features.py", "src/racing_model/model.py", "src/racing_model/track_bias.py", "src/racing_model/backtest.py"],
            "已做近期速度、adjusted speed figure v1、距離/場地適性、負磅、市場、即日偏差及 late flow 特徵。",
            "異常賽標籤、馬場/賽道更細校正、缺失值策略及完整特徵消融仍未系統化。",
            "用更多歷史賽果校準 speed figure par table，加入異常賽標籤及 walk-forward feature ablation。",
            ["時間標準化", "馬場校正", "距離校正", "班次校正", "負磅校正", "馬位轉換", "異常值", "缺失值", "時間衰減", "條件匹配"],
            "極高：特徵清洗係模型成敗核心。",
            "每組新特徵都要做 feature ablation 與 walk-forward。",
            1,
        ),
        spec(
            16,
            "core",
            "模型目標設計",
            STATUS_PARTIAL,
            ["模型預測", "投注決策", "賽果"],
            ["src/racing_model/model.py", "src/racing_model/betting.py", "src/racing_model/model_compare.py"],
            "已輸出勝率、三甲率、公平賠率、EV、價值差距及雙軌模型比較。",
            "排名分布、完成時間模型、馬匹能力分及價值/風險聯合目標仍未完整。",
            "建立同場排名分布與彩池用途對應，明確每個目標服務邊個投注池。",
            ["勝率", "上名率", "排名分布", "完成時間", "馬匹評分", "價值預測"],
            "極高：目標錯會令模型命中率高但 ROI 差。",
            "不同目標要用對應投注池 out-of-sample 指標驗證。",
            2,
        ),
        spec(
            17,
            "core",
            "常見模型方法",
            STATUS_PARTIAL,
            ["特徵矩陣", "賽果", "模型版本"],
            ["src/racing_model/model.py", "src/racing_model/model_compare.py", "src/racing_model/adaptive.py"],
            "已有規則/線性式 pairwise ranking、市場融合及 adaptive policy。",
            "樹模型、Learning-to-rank、Bayesian/TrueSkill、Monte Carlo 賽事模擬及影像模型未接入。",
            "先把現有基準打穩，再加入 ranking/Monte Carlo 實驗並放入 model registry。",
            ["規則型", "線性模型", "樹模型", "排名模型", "貝葉斯", "Elo/TrueSkill", "模擬模型", "影像模型", "混合模型"],
            "中高：方法增加不等於提升，容易過擬合。",
            "新方法必須通過同一 walk-forward/promotion gate。",
            4,
        ),
        spec(
            18,
            "core",
            "評估指標",
            STATUS_PARTIAL,
            ["回測", "walk-forward", "投注 ledger"],
            [
                "src/racing_model/backtest.py",
                "src/racing_model/walk_forward.py",
                "src/racing_model/betting_ledger.py",
                "src/racing_model/pool_replay.py",
                "src/racing_model/promotion_scorecard.py",
            ],
            "已有 Promotion Scorecard v1，合併 Top1/Top3、log loss、Brier、校準、ROI、execution ROI、最大回撤、Sharpe-like、分片 OOS gate，以及 pool replay 資金曲線。",
            "Sharpe-like 仍屬 profit/drawdown 近似值；已有逐票 equity curve，但未有完整波動率、跨賽日置信區間及 promotion gate 硬接入。",
            "下一步把逐票 volatility、日風險置信區間及 bankroll replay 指標納入 promotion gate。",
            ["命中率", "Log Loss", "Brier", "Calibration", "ROI", "EV", "CLV", "最大回撤", "Sharpe-like", "分賽事類型"],
            "極高：無正確評估就不能自我進化。",
            "升級必須通過概率、ROI、回撤及分片指標。",
            1,
        ),
        spec(
            19,
            "core",
            "資金管理",
            STATUS_PARTIAL,
            ["投注決策", "資金設定"],
            ["src/racing_model/betting.py", "src/racing_model/pool_rules.py", "src/racing_model/pool_replay.py", "src/racing_model/betting_ledger.py"],
            "已有 fractional Kelly、單注上限、單場上限、最低投注、弱 EV gate、同馬/同池/同腳位曝險降注、同飛刷新/加注防重覆落飛，以及 pool replay bankroll curve / 日曝險 audit。",
            "每日風險已有 replay audit，但未成為出飛前硬 gate；波動控制仍未完整，實際下注確認已防止重覆落同一張飛。",
            "把日風險上限接入出飛前 gate，並把同飛加注/刷新納入 execution replay 成效報告。",
            ["固定注碼", "比例下注", "Kelly", "最高下注限制", "投注篩選", "分散風險", "紀律"],
            "極高：資金管理錯會令正 EV 模型爆倉。",
            "風險層必須降低最大回撤，且不靠資料洩漏提高 ROI。",
            1,
        ),
        spec(
            20,
            "core",
            "實戰風險",
            STATUS_PARTIAL,
            ["資料質素", "賠率 ticks", "模型報告"],
            ["src/racing_model/error_taxonomy.py", "src/racing_model/feed_health.py", "src/racing_model/walk_forward.py", "src/racing_model/live.py", "src/racing_model/storage.py", "src/racing_model/app_server.py", "src/racing_model/web/app.js"],
            "已有 feed health、錯誤分類、walk-forward、資料品質檢查、HKJC 結果時間窗 guard、官方 void race 識別、已完賽 DB cache guard、官方-only odds auto refresh 及缺失模型自動訓練；未到官方結果時間或 HKJC 未有賽果/void 聲明時不會自動完場。",
            "樣本偏差、市場效率、資料延遲、不可觀測因素、模型漂移及合規風險未成為硬 gate；賽程延誤仍需以 HKJC 官方狀態或結果頁確認。",
            "加入實戰風險 checklist 與 race-level confidence gate，資料不足時自動降注/不下注，並接入 HKJC 官方賽事狀態。",
            ["樣本偏差", "過度擬合", "市場效率", "資料延遲", "不可觀測因素", "模型漂移", "法律合規"],
            "極高：實戰風險會令歷史回測失效。",
            "實戰 gate 要用 replay 檢查 ROI、回撤及棄賽比例。",
            2,
        ),
        spec(
            21,
            "core",
            "最重要核心特徵清單",
            STATUS_PARTIAL,
            ["特徵工程", "賠率", "賽果", "晨操/配備"],
            ["src/racing_model/features.py", "src/racing_model/model.py", "src/racing_model/trip_diagnostics.py", "src/racing_model/pace_profile.py"],
            "已覆蓋近期速度、距離/場地適性、負磅、檔位、步速 profile、節奏投影、升降班、評分變化、隱藏能力、體重、配備、賠率與 late flow。",
            "完整試閘/晨操、血統、即時亮相圈及官方逐段時間仍未全面結構化。",
            "把新增 pace/class 特徵納入 ablation，逐項驗證是否改善 Top1/Top3、ROI、組合彩池排序及 no-bet gate。",
            ["近期速度", "同場同程", "距離適性", "場地適性", "班次升降", "評分變化", "負磅", "檔位", "步速", "跑法", "騎師", "練馬師", "休息日數", "體重", "上仗不利", "配備", "試閘晨操", "即時賠率", "賠率變化", "概率賠率差距"],
            "極高：這是 MVP 方程式的核心輸入清單。",
            "每個核心特徵都要有 ablation 結果和最低樣本數。",
            1,
        ),
        spec(
            22,
            "advanced",
            "市場效率 / 莊家抽水層",
            STATUS_PARTIAL,
            ["HKJC 彩池規則", "投注決策", "回測"],
            ["src/racing_model/pool_rules.py", "src/racing_model/betting.py", "src/racing_model/pool_replay.py"],
            "已加入彩池派彩率、抽水率、最低投注、market buffer 及扣成本後 EV gate。",
            "官方規則覆核、池別敏感度、真實 settlement 及市場效率分層仍未完整。",
            "按 WIN/PLACE/QIN/QPL/TRIO/TCE 等分彩池重播 ROI，抽水後無 edge 即不下注。",
            ["takeout 後 edge", "不同 pool ROI", "抽水成本覆蓋"],
            "極高：估中但 edge 被抽水吃掉仍然會輸。",
            "分彩池扣成本 ROI 必須勝過 raw EV baseline。",
            1,
        ),
        spec(
            23,
            "advanced",
            "臨場資金流模型",
            STATUS_PARTIAL,
            ["賠率 ticks", "HKJC GraphQL/MQTT", "CLV"],
            ["src/racing_model/market_flow.py", "src/racing_model/features.py", "src/racing_model/betting_ledger.py", "tests/test_late_market_flow.py", "tests/test_fast_betting_refresh.py"],
            "已計算最後 5 分鐘、2 分鐘、30 秒賠率異動，並在 UI 顯示 per-runner signal；WIN/PLACE 下注必須有官方 HKJC live source，30 秒 full betting refresh 會同步刷新 open confirmed tickets 的最新彩池賠率/派彩。",
            "尚未可靠分辨真聰明錢/公眾追熱，真實賽日樣本仍少。",
            "累積 live ticks，建立 steam/drift 質素分和 CLV 驗證。",
            ["最後 5 分鐘", "最後 2 分鐘", "最後 30 秒", "聰明錢 vs 公眾追熱", "被壓到無價值即放棄"],
            "極高：臨場資金流可能係 live sniper 的主訊號。",
            "Baseline 必須打贏 No Late Flow，CLV 長期為正才加注。",
            1,
        ),
        spec(
            24,
            "advanced",
            "彩池選擇模型",
            STATUS_PARTIAL,
            ["模型預測", "組合派彩", "投注候選"],
            ["src/racing_model/betting.py", "src/racing_model/exotic_dividends.py", "src/racing_model/pool_replay.py", "src/racing_model/web/app.js"],
            "已產生多彩池候選，並把官方派彩覆蓋率、派彩質素、成本後 EV、所需派彩差、風險扣分、官方價 gate、分池 replay gate、馬場/路程/班次情境切片及 walk-forward pool-choice optimizer 納入 pool-choice 排序；optimizer 會用當時之前的已結算樣本 replay 封池/降注政策，並與 baseline 全買比較 ROI/回撤。",
            "仍未有跨場相關性、切片樣本穩定性檢定、長期 ROI 顯著性及更細 pool 結構 optimizer。",
            "擴大 hit probability x official expected dividend x risk x takeout x contextual replay performance 的 walk-forward 樣本，逐池驗證不下注/升級/降級閾值。",
            ["位置Q", "連贏", "單T/三重彩", "四連環/四重彩", "中獎率 x 派彩 x 風險"],
            "極高：買錯玩法會大幅降低 ROI。",
            "Pool-choice optimizer 必須在 walk-forward replay 中未差過單一彩池 baseline，且切片樣本不足時要能保守 fallback。",
            2,
        ),
        spec(
            25,
            "advanced",
            "組合派彩預測",
            STATUS_PARTIAL,
            ["HKJC 可能派彩", "HKJC MQTT recovery", "最終派彩", "彩池大小"],
            ["src/racing_model/exotic_dividends.py", "src/racing_model/exotic_live.py", "src/racing_model/betting.py", "src/racing_model/pool_replay.py", "tests/test_betting.py", "tests/test_pool_replay.py"],
            "可儲存 probable/final dividends，下注引擎會標示官方即時、賽果派彩、估算或未核實派彩；只有 HKJC GraphQL/MQTT probable 組合派彩可進入即場下注 gate。pool replay 已加入 final dividend audit，並可由 audit 驅動補抓 HKJC 賽果/最終派彩再自動對數；分池 replay gate 會用已結算/等待派彩狀態及本場情境切片控制組合票注碼。",
            "彩池深度、組合結構校準、更完整 probable/final dividend coverage、長期 final-dividend replay 及分切片 ROI 顯著性仍未完整。",
            "擴大 HKJC probable/final dividend 抓取覆蓋，把補抓後的真實 final dividends 納入 QPL/TRIO/TCE/FIRST4/QUARTET 分池/切片 walk-forward 校準。",
            ["組合彩池賠率", "probable dividend", "final dividend", "官方即時派彩"],
            "極高：無派彩就不能正確計組合注碼。",
            "組合 EV 要用真實 final dividend 做 replay 校準。",
            1,
        ),
        spec(
            26,
            "advanced",
            "馬匹狀態即時層",
            STATUS_EXTERNAL,
            ["亮相圈影片", "人工筆記", "入閘前觀察"],
            [],
            "目前未有亮相圈/入閘前狀態輸入。",
            "躁動、出汗、步姿、亮相圈狀態等需要人工或影像資料。",
            "先做有時間戳的人工結構化輸入，再評估是否可用合規影像來源。",
            ["入閘前躁動", "出汗", "步姿", "亮相圈狀態", "人工/影像評分"],
            "中高：臨場狀態有用，但主觀噪音極高。",
            "只能用事前時間戳筆記做 out-of-sample replay。",
            8,
        ),
        spec(
            27,
            "advanced",
            "賽事節奏模擬",
            STATUS_PARTIAL,
            ["沿途位置", "分段時間", "跑法資料"],
            ["src/racing_model/pace.py", "src/racing_model/pace_profile.py", "src/racing_model/betting.py", "src/racing_model/app_server.py"],
            "已升級至 pace simulation v2：結合近 6 場 pace profile、檔位、跑法、同日偏差及模型機率，輸出預計位置、步速形態、塞車/走外風險、步速優勢，並用於組合投注排序。",
            "仍未有逐段時間、彎位搶位、馬群交通路徑及 Monte Carlo replay。",
            "下一步用賽果分段/沿途位校準節奏命中率，再將 pace edge replay 結果納入 promotion scorecard。",
            ["放頭", "跟前", "被困", "末段追勢", "谷草短直路", "沙田泥地 1200"],
            "極高：節奏係組合彩池與短途賽的核心。",
            "Simulation 必須降低 pace 錯誤分類並改善 exotic ROI。",
            2,
        ),
        spec(
            28,
            "advanced",
            "賽道偏差即日更新",
            STATUS_PARTIAL,
            ["同日賽果", "賠率 ticks", "跑法/檔位"],
            ["src/racing_model/track_bias.py", "src/racing_model/features.py", "src/racing_model/walk_forward.py"],
            "已根據同日已完賽場次建立內外檔及步速偏差，並避免使用未來場次。",
            "欄位、場地維修、早段樣本不足和跑法分類仍限制可信度。",
            "逐場 replay 賽日，加入欄位與早段信心分，樣本不足時只作提示不加注。",
            ["內欄快/外疊有利", "前置/後上偏差", "一場完更新下一場"],
            "極高：即日偏差可即場改變下一場下注價值。",
            "No Track Bias 對照必須被樣本外打贏。",
            1,
        ),
        spec(
            29,
            "advanced",
            "騎師 / 練馬師意圖",
            STATUS_PARTIAL,
            ["報名資料", "配備變更", "騎師安排", "晨操密度", "馬房消息"],
            ["src/racing_model/features.py"],
            "目前只有騎師/練馬師歷史勝率，未有明確意圖模型。",
            "熱身、試路程、試配備、搏殺日、主戰騎師選馬等仍未量化。",
            "用升降班、配備變更、騎師 booking 強度、晨操密度建立 intent score。",
            ["熱身", "試閘/試路程", "試配備", "搏殺日", "騎師安排", "晨操密度"],
            "高：意圖錯判會令模型追錯低賠或放過真搏殺馬。",
            "Intent score 要改善 no-bet 與冷門 value 分片。",
            4,
        ),
        spec(
            30,
            "advanced",
            "模型校準",
            STATUS_PARTIAL,
            ["賽果", "模型預測", "walk-forward", "下注建議"],
            ["src/racing_model/evolution.py", "src/racing_model/calibration_gate.py", "src/racing_model/pool_calibration.py", "src/racing_model/betting.py", "src/racing_model/model_registry.py"],
            "已有 Brier、log loss、整體/分片可靠度分桶、WIN/PLACE/組合彩池投注留痕校準、calibration stake gate、promotion calibration blocker、下注時 execution ROI / 回撤升級 blocker，以及 live 同分概率熔斷。",
            "已加入場地、跑道、路程、場地狀況、班次、馬匹數、市場熱門分片、候選模型 OOS reliability artifact、按彩池校準 gate 及即場市場 fallback；仍未按實際組合結構做分層校準。",
            "把組合彩池再拆到 QPL/TRIO/TCE/FIRST4/QUARTET 結構層，並用真實投注回放檢查 Kelly 注碼安全。",
            ["30% 勝率長期是否真贏 30%", "Kelly 安全", "reliability bins", "分片校準", "分彩池校準"],
            "極高：概率未校準會破壞所有 EV 與 Kelly。",
            "可靠度分桶、Brier、log loss 必須樣本外改善。",
            1,
        ),
        spec(
            31,
            "advanced",
            "避免過度擬合",
            STATUS_PARTIAL,
            ["walk-forward", "model registry", "分片回測"],
            ["src/racing_model/model.py", "src/racing_model/walk_forward.py", "src/racing_model/model_registry.py"],
            "已有 walk-forward、candidate OOS slice scorecard、candidate OOS reliability artifact、模型溫度校準序列化、experiment manifest / ablation trail、model registry promotion gate、execution gate，以及受 gate 控制的 CLI/API/UI promote 動作。",
            "候選 OOS reliability 已保存及可阻擋升級；conservative temperature 候選已可保存成正式模型執行策略；每次 registry OOS run 會保存 variants、特徵刪減、temperature、baseline delta 及 gate inputs。",
            "把 experiment manifest 擴展到每次 feature PR/commit 的人工備註與資料版本 hash，並把 promoted model 的校準策略納入長期 drift 監控。",
            ["walk-forward", "out-of-sample", "分場地/距離/班次驗證", "候選可靠度 artifact", "temperature calibration", "experiment manifest", "ablation trail", "防止記住歷史答案"],
            "極高：越迭代未必越準，可能只係過擬合。",
            "所有模型升級必須有 baseline 對照與最低樣本數。",
            1,
        ),
        spec(
            32,
            "advanced",
            "下注組合風險控制",
            STATUS_PARTIAL,
            ["投注候選", "資金設定", "派彩"],
            ["src/racing_model/betting.py", "src/racing_model/betting_ledger.py", "src/racing_model/storage.py", "src/racing_model/pool_replay.py"],
            "已有單注/單場 caps、同一候選建議注碼、同飛刷新/同飛加注防重覆、同一場同一彩池同一馬/組合的 ledger unique guard、膽拖腳/複式結構、horse/pool/combination exposure graph 自動降注，以及 bankroll replay 風控 audit。",
            "bankroll replay 已能檢查 race/horse/pool/combination cap breach；仍未有跨賽事相關曝險及降注前後 A/B 回放。",
            "把 exposure graph 做成降注前/後 A/B replay，驗證最大回撤下降並保留 ROI，並追蹤同飛加注是否改善入飛效率。",
            ["每場總風險", "同一匹馬曝險", "相關組合曝險", "複式/膽拖腳風險"],
            "極高：組合票好易表面分散、實際集中。",
            "bankroll replay 必須降低最大回撤，且保留正 ROI。",
            1,
        ),
        spec(
            33,
            "advanced",
            "錯誤分析資料庫",
            STATUS_PARTIAL,
            ["賽果", "模型預測", "投注結果", "診斷標籤"],
            ["src/racing_model/error_taxonomy.py", "src/racing_model/storage.py", "src/racing_model/evolution.py", "src/racing_model/trip_diagnostics.py"],
            "已有 race_error_reviews 及 /api/error-taxonomy，能分類首選及正 EV 失誤。",
            "分類仍偏 heuristic，未把錯誤類別自動轉成下一輪特徵實驗。",
            "把步速、狀態、賠率、場地、騎師、市場等失誤變成可追蹤實驗 backlog。",
            ["步速估錯", "狀態估錯", "賠率過熱", "場地偏差", "騎師處理", "高估冷門"],
            "高：唔分類錯誤就無法真正進化。",
            "針對性修正後，相同錯誤類別樣本外比例要下降。",
            3,
        ),
        spec(
            34,
            "advanced",
            "下注執行層",
            STATUS_PARTIAL,
            ["投注建議", "賠率 ticks", "最終賠率", "bet ledger"],
            ["src/racing_model/betting_ledger.py", "src/racing_model/storage.py"],
            "betting_recommendations 已儲存建議時賠率，並支援 UI/API 確認下注時注碼、execution CLV；落飛前必須通過 action、官方 live source、所需賠率、正 EV/edge、calibration、exposure、pool-choice gate。賽前最後5分鐘若 confirmed 少過5條，會按接近 gate 程度補足訓練飛，且最少兩條組合飛，30 秒 refresh 會把通過 gate 的 open tickets 更新至最新彩池價。",
            "仍未有自動下注、下注單號、取消/部分成交、以及組合彩池完整執行審計。",
            "加入取消/部分成交狀態、下注單號，並把 latest-pool execution ROI 納入 promotion gate。",
            ["建議時賠率", "落飛模型 gate", "賽前5分鐘訓練補飛", "最新彩池賠率", "最後賠率"],
            "高：最後一刻 tote 變動可吃掉 edge。",
            "slippage-adjusted ROI 要獨立報告並納入 promotion gate。",
            2,
        ),
        spec(
            35,
            "advanced",
            "多目標優化",
            STATUS_PARTIAL,
            ["回測", "walk-forward", "投注 ledger", "風險報告"],
            [
                "src/racing_model/backtest.py",
                "src/racing_model/walk_forward.py",
                "src/racing_model/ev_blackbox.py",
                "src/racing_model/betting.py",
                "src/racing_model/promotion_scorecard.py",
            ],
            "已有多目標 Promotion Scorecard v1，同時檢查 Top1、Top3、ROI、execution ROI、最大回撤、Sharpe-like、分彩池 ROI 及分片 OOS；walk-forward 候選模型排序與 model registry 升級 gate 已加入多目標 OOS 分，唔再只用 Log Loss/Brier 排第一；EV 黑箱訓練已支援逐賽日 micro-tune 及全賽日 final refit，候選按 +EV、平均概率/命中率、ROI、賽事覆蓋率及回撤選擇，避免只追少數高賠票。",
            "仍未把 EV 黑箱候選接入正式 model registry promotion，也未有足夠歷史位置賠率做位置 ROI 長期訓練。",
            "下一步把 EV 黑箱報告接入 UI/model registry，並擴大位置賠率與組合彩池 final dividend 樣本。",
            ["Top1", "Top3", "ROI", "最大回撤", "Sharpe-like", "每種彩池 ROI"],
            "高：只追命中率會傷害 ROI，只追 ROI 可能爆回撤。",
            "所有主目標要過 gate，分池/分片不可明顯惡化。",
            3,
        ),
        spec(
            36,
            "advanced",
            "不下注決策",
            STATUS_DONE,
            ["投注決策", "資料質素", "賽事狀態"],
            ["src/racing_model/betting.py", "src/racing_model/betting_ledger.py", "src/racing_model/web/app.js"],
            "已對弱 EV、弱 edge、已開跑、已完場及資料不足候選輸出不下注/不可下注；落飛 gate 會把未過模型門檻的 positive-stake rows 留作 suggested，不進入派彩對數。EV 黑箱已支援較高賽事覆蓋策略：場場可買，但每張飛仍要過 +EV、概率、賠率及回撤約束。",
            "仍需要 race-level edge summary、資料噪音信心分、相關曝險後的整場降注/不下注，以及 bet-time odds/slippage 驗證。",
            "加入全場 edge summary，模型無明顯優勢或曝險過度集中時直接降注或不下注，並在 UI 顯示 gate 擋飛原因。",
            ["場場可買但要 +EV", "無 edge 不買", "勝率與 ROI 同時考慮"],
            "極高：識得不下注係長期 ROI 核心。",
            "no-bet gate 要提升 ROI/回撤，不能靠排除虧損賽後資料。",
            1,
        ),
    ]
    return [item(**row) for row in rows]


def spec(
    item_id: int,
    category: str,
    name: str,
    status: str,
    data_sources: list[str],
    supported_files: list[str],
    current_support: str,
    gaps: str,
    next_steps: str,
    sub_items: list[str],
    model_risk: str,
    validation_gate: str,
    priority: int,
) -> dict[str, Any]:
    return {
        "item_id": item_id,
        "category": category,
        "name": name,
        "status": status,
        "data_sources": data_sources,
        "supported_files": supported_files,
        "current_support": current_support,
        "gaps": gaps,
        "next_steps": next_steps,
        "sub_items": sub_items,
        "model_risk": model_risk,
        "validation_gate": validation_gate,
        "priority": priority,
    }


def item(
    item_id: int,
    category: str,
    name: str,
    status: str,
    data_sources: list[str],
    supported_files: list[str],
    current_support: str,
    gaps: str,
    next_steps: str,
    sub_items: list[str],
    model_risk: str,
    validation_gate: str,
    priority: int,
) -> dict[str, Any]:
    default_score = STATUS_WEIGHTS[status]
    override_score, override_reason = MATURITY_OVERRIDES.get(item_id, (default_score, "按目前狀態權重計算。"))
    maturity_score = max(0.0, min(float(override_score), STATUS_WEIGHTS[STATUS_DONE]))
    return {
        "id": item_id,
        "category": category,
        "category_label": "核心方程式主項" if category == "core" else "進階實戰主項",
        "name": name,
        "status": status,
        "status_key": status_key(status),
        "maturity_score": round(maturity_score, 4),
        "maturity_percent": round(maturity_score * 100, 1),
        "maturity_reason": override_reason,
        "data_sources": data_sources,
        "supported_files": supported_files,
        "current_support": current_support,
        "gaps": gaps,
        "next_steps": next_steps,
        "sub_items": sub_items,
        "model_risk": model_risk,
        "validation_gate": validation_gate,
        "priority": priority,
    }


def status_key(status: str) -> str:
    return {
        STATUS_DONE: "done",
        STATUS_PARTIAL: "partial",
        STATUS_MISSING: "missing",
        STATUS_EXTERNAL: "external",
    }[status]
