from __future__ import annotations

import sqlite3
from typing import Any

from .storage import fetch_all


STATUS_DONE = "已完成"
STATUS_PARTIAL = "部分完成"
STATUS_MISSING = "未完成"
STATUS_EXTERNAL = "需要外部數據"

STATUS_WEIGHTS = {
    STATUS_DONE: 1.0,
    STATUS_PARTIAL: 0.5,
    STATUS_EXTERNAL: 0.15,
    STATUS_MISSING: 0.0,
}


def build_coverage_report(conn: sqlite3.Connection) -> dict[str, Any]:
    items = coverage_items()
    status_counts = {status: 0 for status in STATUS_WEIGHTS}
    for item_data in items:
        status_counts[str(item_data["status"])] += 1

    weighted = sum(STATUS_WEIGHTS[str(item_data["status"])] for item_data in items)
    max_score = len(items) or 1
    blocked = [item_data for item_data in items if item_data["status"] in {STATUS_MISSING, STATUS_EXTERNAL}]
    priority_items = sorted(
        blocked,
        key=lambda item_data: (int(item_data["priority"]), int(item_data["id"])),
    )[:8]

    return {
        "title": "方程式覆蓋率 / 盲點報告",
        "objective": "以 36 個賽馬方程式主項追蹤模型補洞進度；所有補洞都要用 walk-forward / out-of-sample 證明提升。",
        "status_labels": {
            "done": STATUS_DONE,
            "partial": STATUS_PARTIAL,
            "missing": STATUS_MISSING,
            "external": STATUS_EXTERNAL,
        },
        "summary": {
            "target_groups": 36,
            "total_groups": len(items),
            "core_groups": sum(1 for item_data in items if item_data["category"] == "core"),
            "blind_spot_groups": sum(1 for item_data in items if item_data["category"] == "advanced"),
            "coverage_score": round(weighted / max_score, 4),
            "status_counts": status_counts,
            "database": database_snapshot(conn),
        },
        "items": items,
        "priority_next_steps": [
            {
                "id": item_data["id"],
                "name": item_data["name"],
                "status": item_data["status"],
                "model_risk": item_data["model_risk"],
                "next_steps": item_data["next_steps"],
                "validation_gate": item_data["validation_gate"],
            }
            for item_data in priority_items
        ],
    }


def database_snapshot(conn: sqlite3.Connection) -> dict[str, int]:
    tables = [
        "races",
        "runners",
        "results",
        "workouts",
        "odds_ticks",
        "raw_snapshots",
        "race_status",
        "model_registry_runs",
        "betting_recommendations",
        "exotic_dividends",
    ]
    snapshot: dict[str, int] = {}
    for table in tables:
        try:
            snapshot[table] = int(fetch_all(conn, f"SELECT count(*) AS n FROM {table}")[0]["n"])
        except sqlite3.Error:
            snapshot[table] = 0
    return snapshot


def coverage_items() -> list[dict[str, Any]]:
    rows = [
        spec(
            1,
            "core",
            "賽事基本條件",
            STATUS_PARTIAL,
            ["賽事資料", "HKJC 排位表", "賽果資料", "天氣資料"],
            ["src/racing_model/storage.py", "src/racing_model/features.py", "src/racing_model/weather.py"],
            "已儲存馬場、賽道、距離、場地狀態、班次、賽事狀態及部分天氣顯示。",
            "馬場幾何、欄位、坡度、獎金、日夜賽、溫濕度與即日場地變化仍未完整進入模型。",
            "把場地、跑道、距離、班次、獎金、賽事時間及天氣轉成分桶特徵，按馬場/距離做 walk-forward 分片。",
            ["馬場", "跑道類型", "場地狀態", "賽程距離", "賽事級別", "獎金", "參賽馬數", "賽事時間"],
            "高：基本條件係所有歷史表現能否轉移到今場的前提。",
            "分馬場、距離、場地狀態的 log loss / Brier / ROI 必須樣本外改善。",
            2,
        ),
        spec(
            2,
            "core",
            "馬匹本身能力",
            STATUS_PARTIAL,
            ["參賽馬資料", "賽果資料", "晨操/試閘", "獸醫資料"],
            ["src/racing_model/features.py", "src/racing_model/model.py", "src/racing_model/trip_diagnostics.py", "data/sample/runners.csv"],
            "已用官方評分、年齡、性別、近期速度、近績、負磅及同場 pairwise ranking 建立基礎能力。",
            "耐力、爆發力、穩定性、體重變化、健康紀錄、心理性格、起步、轉彎、換腳等仍未完整建模。",
            "建立標準化速度評分、馬匹能力曲線、體重/健康/跑法特徵，並用特徵消融驗證。",
            ["整體實力評分", "速度能力", "耐力", "爆發力", "穩定性", "年齡/性別", "體重", "健康", "心理性格", "跑法", "轉彎", "起步", "換腳平衡"],
            "極高：馬匹能力估錯會污染勝率、位置率及所有組合彩池。",
            "能力特徵必須打贏 market-only 與現有 baseline，並改善三甲校準。",
            1,
        ),
        spec(
            3,
            "core",
            "近期狀態",
            STATUS_PARTIAL,
            ["賽果資料", "晨操資料", "試閘資料", "獸醫報告"],
            ["src/racing_model/features.py", "src/racing_model/trip_diagnostics.py", "data/sample/workouts.csv"],
            "已使用近績、近期速度及操練分數。",
            "休息日數、狀態走勢、上仗不利解讀、試閘姿態、晨操強度及賽後恢復仍較淺。",
            "加入休息週期、狀態斜率、復出場次、上仗受阻/熱身標籤及獸醫旗標。",
            ["近績", "狀態走勢", "休息日數", "試閘/晨操", "上仗解讀", "賽後恢復"],
            "高：近期狀態錯判會令過時能力分變成假 value。",
            "復出馬、密跑馬及轉勢馬分片要在 out-of-sample 改善。",
            3,
        ),
        spec(
            4,
            "core",
            "騎師因素",
            STATUS_PARTIAL,
            ["參賽馬資料", "賽果資料", "HKJC 排位表/賽果"],
            ["src/racing_model/features.py"],
            "已用匯入賽果計算騎師歷史勝率，UI 顯示中文騎師名。",
            "人馬配合、馬場/距離適性、當日手風、決策能力及騎師動機仍未完整。",
            "加入滾動騎師狀態、騎師與馬匹配合、騎練組合、當日成績及換騎師訊號。",
            ["整體能力", "人馬配合", "馬場適性", "當日狀態", "決策能力", "騎師動機"],
            "中高：騎師變動經常與市場資金流及部署意圖有關。",
            "換騎師/騎練組合分片必須改善且有最低樣本數保護。",
            5,
        ),
        spec(
            5,
            "core",
            "練馬師因素",
            STATUS_PARTIAL,
            ["參賽馬資料", "賽果資料", "HKJC 排位表/賽果"],
            ["src/racing_model/features.py"],
            "已用匯入賽果計算練馬師歷史勝率，UI 顯示中文練馬師名。",
            "近期馬房狀態、部署模式、騎練組合、新馬/轉倉改善未完整。",
            "加入滾動馬房勝率、部署模式、升降班策略、轉倉及新馬特徵。",
            ["整體成績", "馬房狀態", "部署模式", "騎練組合", "新馬/轉倉馬"],
            "中高：馬房部署會直接影響是否搏殺。",
            "馬房狀態及部署特徵要在 walk-forward 提升 no-bet 精準度。",
            5,
        ),
        spec(
            6,
            "core",
            "負磅與讓磅",
            STATUS_PARTIAL,
            ["參賽馬資料", "HKJC 排位表"],
            ["src/racing_model/features.py", "src/racing_model/scrapers/hkjc.py", "src/racing_model/trip_diagnostics.py"],
            "已使用實際負磅作為數值特徵。",
            "上仗負磅變化、見習減磅、馬匹體重與負磅比例、距離/班次互動仍未完整。",
            "加入負磅變化、減磅欄位、體重比例及按距離/班次的磅數校正。",
            ["實際負磅", "讓磅優勢", "體重與負磅比例", "距離與負磅", "班次與負磅"],
            "中：未標準化的磅數容易被模型錯解。",
            "負磅分桶及距離互動要改善校準才可提升權重。",
            7,
        ),
        spec(
            7,
            "core",
            "排位與檔位",
            STATUS_PARTIAL,
            ["參賽馬資料", "賽事資料", "賽果資料"],
            ["src/racing_model/features.py", "src/racing_model/track_bias.py"],
            "已加入內檔/外檔旗標，並有即日偏差引擎的初步檔位訊號。",
            "未按馬場、距離、欄位、場地狀態、鄰近快馬及樣本大小建立完整檔位模型。",
            "建立馬場/距離/欄位/場地狀態的檔位偏差表，並加入跑法與鄰近馬互動。",
            ["檔位", "馬場檔位偏差", "跑法與檔位配合", "鄰近馬影響", "歷史檔位統計"],
            "高：香港賽事檔位足以改變排名及組合機率。",
            "分檔位 ROI、三甲命中及即日偏差 replay 必須改善。",
            2,
        ),
        spec(
            8,
            "core",
            "步速與賽事形態",
            STATUS_PARTIAL,
            ["參賽馬資料", "賽果分段", "沿途位置"],
            ["src/racing_model/features.py", "src/racing_model/track_bias.py", "src/racing_model/error_taxonomy.py", "src/racing_model/trip_diagnostics.py"],
            "已用 running_style 建立基本步速壓力，錯誤分類亦可標記 pace 相關失誤。",
            "跑法經常缺失；首 400m、入彎位置、受阻風險及交通模擬仍未完整。",
            "由歷史沿途位置/分段推斷跑法，建立 pace map、位置預測及受阻風險。",
            ["早段步速", "領放壓力", "跑法分布", "賽事節奏", "位置預測", "受阻風險"],
            "極高：步速錯判係組合玩法同冷門錯判的主要來源。",
            "加入後 pace 類錯誤要在樣本外下降，且組合 ROI 不可惡化。",
            1,
        ),
        spec(
            9,
            "core",
            "血統因素",
            STATUS_MISSING,
            ["血統資料", "外地馬資料", "家族賽績"],
            [],
            "目前未有血統資料表或血統特徵。",
            "父系/母系距離、場地、早熟/遲熟、兄弟姐妹表現及外地馬轉場訊號未接入。",
            "先設計 pedigree 表與手動匯入格式，再用新馬/初跑途程分片測試。",
            ["父系", "母系", "家族賽績", "新馬與轉程判斷"],
            "中：對新馬、外地馬、初跑泥地/增程特別重要。",
            "只在新馬/少賽績分片通過 out-of-sample 才可使用。",
            8,
        ),
        spec(
            10,
            "core",
            "配備與裝備",
            STATUS_PARTIAL,
            ["參賽馬資料", "HKJC 排位表"],
            ["src/racing_model/storage.py", "src/racing_model/scrapers/hkjc.py"],
            "已儲存配備欄位。",
            "首次戴、重戴、除去、多項配備同改及蹄鐵變化未轉成模型特徵。",
            "建立配備歷史與變動特徵，按配備類型、班次、距離做消融測試。",
            ["眼罩", "面箍/頭罩", "舌帶", "交叉鼻箍", "耳塞", "蹄鐵", "配備變動信號"],
            "中：高訊號但容易小樣本過擬合。",
            "配備特徵要通過 walk-forward 與小樣本收縮保護。",
            6,
        ),
        spec(
            11,
            "core",
            "班次與評分變化",
            STATUS_PARTIAL,
            ["賽事資料", "參賽馬資料", "賽果資料"],
            ["src/racing_model/features.py", "src/racing_model/model.py", "src/racing_model/trip_diagnostics.py"],
            "已使用官方評分與賽事班次，模型透過同場 pairwise ranking 比較對手。",
            "升降班、評分升跌、跌到可搏水平及隱藏能力仍未完整量化。",
            "加入評分變化、升降班、班次深度、上仗不利但評分下調等特徵。",
            ["升班", "降班", "評分升跌", "隱藏能力"],
            "高：評分與班次係香港讓賽核心。",
            "分班次 log loss、ROI、no-bet 準確度必須改善。",
            2,
        ),
        spec(
            12,
            "core",
            "賠率與市場資訊",
            STATUS_DONE,
            ["賠率 ticks", "HKJC GraphQL", "HKJC MQTT", "最終賠率"],
            ["src/racing_model/odds.py", "src/racing_model/live.py", "src/racing_model/market_flow.py", "src/racing_model/features.py"],
            "已儲存獨贏/位置 ticks，計算市場隱含概率、EV、價值差距及臨場資金流。",
            "成交量、真正大戶資金、公眾追熱識別及最終 CLV 樣本仍不足。",
            "累積真實賽日 ticks，分最後 5/2/0.5 分鐘驗證資金流與 CLV。",
            ["獨贏賠率", "位置賠率", "賠率異動", "成交量", "賠率價值", "水位與抽水", "熱門偏差"],
            "極高：市場係模型要打贏的主要 baseline。",
            "任何特徵模型都要打贏 market-only walk-forward。",
            1,
        ),
        spec(
            13,
            "core",
            "投注類型",
            STATUS_PARTIAL,
            ["模型預測", "組合派彩", "投注決策"],
            ["src/racing_model/betting.py", "src/racing_model/exotic_dividends.py", "src/racing_model/betting_ledger.py"],
            "已支援 WIN/PLACE 及 QIN/QPL/FCT/TRIO/TCE/FIRST4/QUARTET 候選與部分結算。",
            "多場投注、跨場相關性、排名分布校準及每個彩池的最終 ROI 尚未完整。",
            "完善組合彩池派彩、按池 replay、跨彩池/跨馬曝險及多場投注先暫不做。",
            ["獨贏", "位置", "連贏", "位置Q", "二重彩", "三連彩", "三重彩", "四連環/四重彩", "多場投注"],
            "極高：選錯彩池會把正確觀點變成負 EV。",
            "每個彩池都要有 hit rate、ROI、回撤及派彩校準。",
            2,
        ),
        spec(
            14,
            "core",
            "資料來源",
            STATUS_PARTIAL,
            ["HKJC 賽事/賽果", "賠率", "晨操", "天氣", "新聞/影片"],
            ["src/racing_model/scrapers/hkjc.py", "src/racing_model/storage.py", "src/racing_model/weather.py"],
            "已有 HKJC racecard/results/trackwork parser、odds providers、raw snapshot 及天氣顯示。",
            "影片、獸醫報告結構化、完整分段、新聞/馬房消息、成交量及場地即時資料仍不足。",
            "建立資料來源清單與品質分，缺資料時降低信心或不下注。",
            ["官方賽績", "分段時間", "賽事影片", "獸醫報告", "試閘", "晨操", "天氣", "即時場地", "賠率", "新聞馬房消息"],
            "極高：資料品質差會直接污染回測與實戰。",
            "所有新資料源要有 raw snapshot、parser test 及缺失值處理。",
            3,
        ),
        spec(
            15,
            "core",
            "資料清洗與特徵工程",
            STATUS_PARTIAL,
            ["賽果資料", "賠率 ticks", "特徵工程"],
            ["src/racing_model/features.py", "src/racing_model/model.py", "src/racing_model/track_bias.py", "src/racing_model/backtest.py"],
            "已做近期速度、adjusted speed figure v1、距離/場地適性、負磅、市場、即日偏差及 late flow 特徵。",
            "異常賽標籤、馬場/賽道更細校正、缺失值策略及完整特徵消融仍未系統化。",
            "用更多歷史賽果校準 speed figure par table，加入異常賽標籤及 walk-forward feature ablation。",
            ["時間標準化", "馬場校正", "距離校正", "班次校正", "負磅校正", "馬位轉換", "異常值", "缺失值", "時間衰減", "條件匹配"],
            "極高：特徵清洗係模型成敗核心。",
            "每組新特徵都要做 feature ablation 與 walk-forward。",
            1,
        ),
        spec(
            16,
            "core",
            "模型目標設計",
            STATUS_PARTIAL,
            ["模型預測", "投注決策", "賽果"],
            ["src/racing_model/model.py", "src/racing_model/betting.py", "src/racing_model/model_compare.py"],
            "已輸出勝率、三甲率、公平賠率、EV、價值差距及雙軌模型比較。",
            "排名分布、完成時間模型、馬匹能力分及價值/風險聯合目標仍未完整。",
            "建立同場排名分布與彩池用途對應，明確每個目標服務邊個投注池。",
            ["勝率", "上名率", "排名分布", "完成時間", "馬匹評分", "價值預測"],
            "極高：目標錯會令模型命中率高但 ROI 差。",
            "不同目標要用對應投注池 out-of-sample 指標驗證。",
            2,
        ),
        spec(
            17,
            "core",
            "常見模型方法",
            STATUS_PARTIAL,
            ["特徵矩陣", "賽果", "模型版本"],
            ["src/racing_model/model.py", "src/racing_model/model_compare.py", "src/racing_model/adaptive.py"],
            "已有規則/線性式 pairwise ranking、市場融合及 adaptive policy。",
            "樹模型、Learning-to-rank、Bayesian/TrueSkill、Monte Carlo 賽事模擬及影像模型未接入。",
            "先把現有基準打穩，再加入 ranking/Monte Carlo 實驗並放入 model registry。",
            ["規則型", "線性模型", "樹模型", "排名模型", "貝葉斯", "Elo/TrueSkill", "模擬模型", "影像模型", "混合模型"],
            "中高：方法增加不等於提升，容易過擬合。",
            "新方法必須通過同一 walk-forward/promotion gate。",
            4,
        ),
        spec(
            18,
            "core",
            "評估指標",
            STATUS_PARTIAL,
            ["回測", "walk-forward", "投注 ledger"],
            [
                "src/racing_model/backtest.py",
                "src/racing_model/walk_forward.py",
                "src/racing_model/betting_ledger.py",
                "src/racing_model/pool_replay.py",
                "src/racing_model/promotion_scorecard.py",
            ],
            "已有 Promotion Scorecard v1，合併 Top1/Top3、log loss、Brier、校準、ROI、execution ROI、最大回撤、Sharpe-like 及分片 OOS gate。",
            "Sharpe-like 仍屬 profit/drawdown 近似值，未有完整逐票波動率及跨賽日置信區間。",
            "下一步把逐票 equity curve / volatility 及置信區間納入 promotion gate。",
            ["命中率", "Log Loss", "Brier", "Calibration", "ROI", "EV", "CLV", "最大回撤", "Sharpe-like", "分賽事類型"],
            "極高：無正確評估就不能自我進化。",
            "升級必須通過概率、ROI、回撤及分片指標。",
            1,
        ),
        spec(
            19,
            "core",
            "資金管理",
            STATUS_PARTIAL,
            ["投注決策", "資金設定"],
            ["src/racing_model/betting.py", "src/racing_model/pool_rules.py"],
            "已有 fractional Kelly、單注上限、單場上限、最低投注、弱 EV gate，以及同馬/同池/同腳位曝險降注。",
            "每日風險、波動控制、資金曲線 replay 及實際落注確認仍未完整。",
            "加入日風險上限、bankroll replay 及 bet-time confirmation。",
            ["固定注碼", "比例下注", "Kelly", "最高下注限制", "投注篩選", "分散風險", "紀律"],
            "極高：資金管理錯會令正 EV 模型爆倉。",
            "風險層必須降低最大回撤，且不靠資料洩漏提高 ROI。",
            1,
        ),
        spec(
            20,
            "core",
            "實戰風險",
            STATUS_PARTIAL,
            ["資料質素", "賠率 ticks", "模型報告"],
            ["src/racing_model/error_taxonomy.py", "src/racing_model/feed_health.py", "src/racing_model/walk_forward.py"],
            "已有 feed health、錯誤分類、walk-forward 及資料品質檢查。",
            "樣本偏差、市場效率、資料延遲、不可觀測因素、模型漂移及合規風險未成為硬 gate。",
            "加入實戰風險 checklist 與 race-level confidence gate，資料不足時自動降注/不下注。",
            ["樣本偏差", "過度擬合", "市場效率", "資料延遲", "不可觀測因素", "模型漂移", "法律合規"],
            "極高：實戰風險會令歷史回測失效。",
            "實戰 gate 要用 replay 檢查 ROI、回撤及棄賽比例。",
            2,
        ),
        spec(
            21,
            "core",
            "最重要核心特徵清單",
            STATUS_PARTIAL,
            ["特徵工程", "賠率", "賽果", "晨操/配備"],
            ["src/racing_model/features.py", "src/racing_model/model.py", "src/racing_model/trip_diagnostics.py"],
            "已覆蓋近期速度、距離/場地適性、負磅、檔位、騎師/練馬師勝率、操練、配備儲存、賠率與 late flow。",
            "同場同程、班次升降、官方評分變化、體重變化、上仗受阻、完整試閘/晨操仍未完成。",
            "把 20 個核心特徵列成 feature backlog，逐項做資料接入、特徵消融及分片驗證。",
            ["近期速度", "同場同程", "距離適性", "場地適性", "班次升降", "評分變化", "負磅", "檔位", "步速", "跑法", "騎師", "練馬師", "休息日數", "體重", "上仗不利", "配備", "試閘晨操", "即時賠率", "賠率變化", "概率賠率差距"],
            "極高：這是 MVP 方程式的核心輸入清單。",
            "每個核心特徵都要有 ablation 結果和最低樣本數。",
            1,
        ),
        spec(
            22,
            "advanced",
            "市場效率 / 莊家抽水層",
            STATUS_PARTIAL,
            ["HKJC 彩池規則", "投注決策", "回測"],
            ["src/racing_model/pool_rules.py", "src/racing_model/betting.py", "src/racing_model/pool_replay.py"],
            "已加入彩池派彩率、抽水率、最低投注、market buffer 及扣成本後 EV gate。",
            "官方規則覆核、池別敏感度、真實 settlement 及市場效率分層仍未完整。",
            "按 WIN/PLACE/QIN/QPL/TRIO/TCE 等分彩池重播 ROI，抽水後無 edge 即不下注。",
            ["takeout 後 edge", "不同 pool ROI", "抽水成本覆蓋"],
            "極高：估中但 edge 被抽水吃掉仍然會輸。",
            "分彩池扣成本 ROI 必須勝過 raw EV baseline。",
            1,
        ),
        spec(
            23,
            "advanced",
            "臨場資金流模型",
            STATUS_PARTIAL,
            ["賠率 ticks", "HKJC GraphQL/MQTT", "CLV"],
            ["src/racing_model/market_flow.py", "src/racing_model/features.py", "tests/test_late_market_flow.py"],
            "已計算最後 5 分鐘、2 分鐘、30 秒賠率異動，並在 UI 顯示 per-runner signal。",
            "尚未可靠分辨真聰明錢/公眾追熱，真實賽日樣本仍少。",
            "累積 live ticks，建立 steam/drift 質素分和 CLV 驗證。",
            ["最後 5 分鐘", "最後 2 分鐘", "最後 30 秒", "聰明錢 vs 公眾追熱", "被壓到無價值即放棄"],
            "極高：臨場資金流可能係 live sniper 的主訊號。",
            "Baseline 必須打贏 No Late Flow，CLV 長期為正才加注。",
            1,
        ),
        spec(
            24,
            "advanced",
            "彩池選擇模型",
            STATUS_PARTIAL,
            ["模型預測", "組合派彩", "投注候選"],
            ["src/racing_model/betting.py", "src/racing_model/exotic_dividends.py"],
            "已產生多彩池候選，並把 probable/final dividend 接入有資料的候選。",
            "缺少完整 pool-choice optimizer，同一觀點未能穩定選出最佳彩池或不下注。",
            "用 hit probability x expected dividend x risk 做跨彩池排序，無 edge 時跳過。",
            ["位置Q", "連贏", "單T/三重彩", "四連環/四重彩", "中獎率 x 派彩 x 風險"],
            "極高：買錯玩法會大幅降低 ROI。",
            "Pool-choice replay 必須勝過單一彩池 baseline。",
            2,
        ),
        spec(
            25,
            "advanced",
            "組合派彩預測",
            STATUS_PARTIAL,
            ["HKJC 可能派彩", "HKJC MQTT recovery", "最終派彩", "彩池大小"],
            ["src/racing_model/exotic_dividends.py", "src/racing_model/exotic_live.py", "src/racing_model/betting.py"],
            "可儲存 probable/final/estimated dividends，並用於組合候選 EV。",
            "彩池深度、最終派彩自動補完、估算模型校準仍未完整。",
            "驗證 live probable dividend 來源，補最終派彩結算與按池校準。",
            ["組合彩池賠率", "probable dividend", "final dividend", "派彩估算"],
            "極高：無派彩就不能正確計組合注碼。",
            "組合 EV 要用真實 final dividend 做 replay 校準。",
            1,
        ),
        spec(
            26,
            "advanced",
            "馬匹狀態即時層",
            STATUS_EXTERNAL,
            ["亮相圈影片", "人工筆記", "入閘前觀察"],
            [],
            "目前未有亮相圈/入閘前狀態輸入。",
            "躁動、出汗、步姿、亮相圈狀態等需要人工或影像資料。",
            "先做有時間戳的人工結構化輸入，再評估是否可用合規影像來源。",
            ["入閘前躁動", "出汗", "步姿", "亮相圈狀態", "人工/影像評分"],
            "中高：臨場狀態有用，但主觀噪音極高。",
            "只能用事前時間戳筆記做 out-of-sample replay。",
            8,
        ),
        spec(
            27,
            "advanced",
            "賽事節奏模擬",
            STATUS_PARTIAL,
            ["沿途位置", "分段時間", "跑法資料"],
            ["src/racing_model/pace.py", "src/racing_model/betting.py", "src/racing_model/app_server.py"],
            "已建立簡化 pace simulation，輸出預計位置、跑法角色、塞車/走外風險，並接入 API 與組合投注候選。",
            "仍未有逐段時間、彎位搶位、馬群交通路徑及 Monte Carlo replay。",
            "下一步用賽果分段/沿途位校準節奏命中率，再把 pace edge 納入組合彩池排序。",
            ["放頭", "跟前", "被困", "末段追勢", "谷草短直路", "沙田泥地 1200"],
            "極高：節奏係組合彩池與短途賽的核心。",
            "Simulation 必須降低 pace 錯誤分類並改善 exotic ROI。",
            2,
        ),
        spec(
            28,
            "advanced",
            "賽道偏差即日更新",
            STATUS_PARTIAL,
            ["同日賽果", "賠率 ticks", "跑法/檔位"],
            ["src/racing_model/track_bias.py", "src/racing_model/features.py", "src/racing_model/walk_forward.py"],
            "已根據同日已完賽場次建立內外檔及步速偏差，並避免使用未來場次。",
            "欄位、場地維修、早段樣本不足和跑法分類仍限制可信度。",
            "逐場 replay 賽日，加入欄位與早段信心分，樣本不足時只作提示不加注。",
            ["內欄快/外疊有利", "前置/後上偏差", "一場完更新下一場"],
            "極高：即日偏差可即場改變下一場下注價值。",
            "No Track Bias 對照必須被樣本外打贏。",
            1,
        ),
        spec(
            29,
            "advanced",
            "騎師 / 練馬師意圖",
            STATUS_PARTIAL,
            ["報名資料", "配備變更", "騎師安排", "晨操密度", "馬房消息"],
            ["src/racing_model/features.py"],
            "目前只有騎師/練馬師歷史勝率，未有明確意圖模型。",
            "熱身、試路程、試配備、搏殺日、主戰騎師選馬等仍未量化。",
            "用升降班、配備變更、騎師 booking 強度、晨操密度建立 intent score。",
            ["熱身", "試閘/試路程", "試配備", "搏殺日", "騎師安排", "晨操密度"],
            "高：意圖錯判會令模型追錯低賠或放過真搏殺馬。",
            "Intent score 要改善 no-bet 與冷門 value 分片。",
            4,
        ),
        spec(
            30,
            "advanced",
            "模型校準",
            STATUS_PARTIAL,
            ["賽果", "模型預測", "walk-forward", "下注建議"],
            ["src/racing_model/evolution.py", "src/racing_model/calibration_gate.py", "src/racing_model/betting.py", "src/racing_model/model_registry.py"],
            "已有 Brier、log loss、可靠度分桶、calibration stake gate、promotion calibration blocker，以及下注時 execution ROI / 回撤升級 blocker。",
            "校準 gate 仍以歷史整體分桶為主，未做到分彩池、分場地、分距離及 OOS candidate calibration artifact。",
            "把 calibration gate 拆成 WIN/PLACE/組合、場地/距離分片，並保存候選模型樣本外可靠度分桶。",
            ["30% 勝率長期是否真贏 30%", "Kelly 安全", "reliability bins"],
            "極高：概率未校準會破壞所有 EV 與 Kelly。",
            "可靠度分桶、Brier、log loss 必須樣本外改善。",
            1,
        ),
        spec(
            31,
            "advanced",
            "避免過度擬合",
            STATUS_PARTIAL,
            ["walk-forward", "model registry", "分片回測"],
            ["src/racing_model/walk_forward.py", "src/racing_model/model_registry.py"],
            "已有 walk-forward、model registry promotion gate、execution gate，以及受 gate 控制的 CLI/API/UI promote 動作。",
            "未有每次權重/特徵改動的完整實驗紀錄要求，溫度校準候選仍未能保存成正式模型策略。",
            "把 promote 連到 candidate artifact、校準策略保存及更細分片 gate，未過樣本外、分片及 execution gate 就不能替換模型。",
            ["walk-forward", "out-of-sample", "分場地/距離/班次驗證", "防止記住歷史答案"],
            "極高：越迭代未必越準，可能只係過擬合。",
            "所有模型升級必須有 baseline 對照與最低樣本數。",
            1,
        ),
        spec(
            32,
            "advanced",
            "下注組合風險控制",
            STATUS_PARTIAL,
            ["投注候選", "資金設定", "派彩"],
            ["src/racing_model/betting.py", "src/racing_model/betting_ledger.py"],
            "已有單注/單場 caps、同一候選建議注碼、膽拖腳/複式結構，以及 horse/pool/combination exposure graph 自動降注。",
            "仍未有完整日風險、跨賽事相關曝險、實際下注確認及 bankroll replay 證明。",
            "把 exposure graph 接入 bankroll replay，驗證降注後是否降低最大回撤並保留 ROI。",
            ["每場總風險", "同一匹馬曝險", "相關組合曝險", "複式/膽拖腳風險"],
            "極高：組合票好易表面分散、實際集中。",
            "bankroll replay 必須降低最大回撤，且保留正 ROI。",
            1,
        ),
        spec(
            33,
            "advanced",
            "錯誤分析資料庫",
            STATUS_PARTIAL,
            ["賽果", "模型預測", "投注結果", "診斷標籤"],
            ["src/racing_model/error_taxonomy.py", "src/racing_model/storage.py", "src/racing_model/evolution.py", "src/racing_model/trip_diagnostics.py"],
            "已有 race_error_reviews 及 /api/error-taxonomy，能分類首選及正 EV 失誤。",
            "分類仍偏 heuristic，未把錯誤類別自動轉成下一輪特徵實驗。",
            "把步速、狀態、賠率、場地、騎師、市場等失誤變成可追蹤實驗 backlog。",
            ["步速估錯", "狀態估錯", "賠率過熱", "場地偏差", "騎師處理", "高估冷門"],
            "高：唔分類錯誤就無法真正進化。",
            "針對性修正後，相同錯誤類別樣本外比例要下降。",
            3,
        ),
        spec(
            34,
            "advanced",
            "下注執行層",
            STATUS_PARTIAL,
            ["投注建議", "賠率 ticks", "最終賠率", "bet ledger"],
            ["src/racing_model/betting_ledger.py", "src/racing_model/storage.py"],
            "betting_recommendations 已儲存建議時賠率，並支援 UI/API 確認下注時賠率、下注時注碼及 execution CLV。",
            "仍未有自動下注、下注單號、取消/部分成交、以及組合彩池完整執行審計。",
            "加入取消/部分成交狀態、下注單號，並把 execution ROI 納入 promotion gate。",
            ["建議時賠率", "下注時賠率", "最後賠率", "30 秒更新仍可能滑價"],
            "高：最後一刻 tote 變動可吃掉 edge。",
            "slippage-adjusted ROI 要獨立報告並納入 promotion gate。",
            2,
        ),
        spec(
            35,
            "advanced",
            "多目標優化",
            STATUS_PARTIAL,
            ["回測", "walk-forward", "投注 ledger", "風險報告"],
            [
                "src/racing_model/backtest.py",
                "src/racing_model/walk_forward.py",
                "src/racing_model/betting.py",
                "src/racing_model/promotion_scorecard.py",
            ],
            "已有多目標 Promotion Scorecard v1，同時檢查 Top1、Top3、ROI、execution ROI、最大回撤、Sharpe-like、分彩池 ROI 及分片 OOS。",
            "仍未把多目標權重自動反饋到訓練目標，暫時是 gate / scorecard 層。",
            "下一步把 scorecard 結果回饋到候選模型搜尋及注碼策略調參。",
            ["Top1", "Top3", "ROI", "最大回撤", "Sharpe-like", "每種彩池 ROI"],
            "高：只追命中率會傷害 ROI，只追 ROI 可能爆回撤。",
            "所有主目標要過 gate，分池/分片不可明顯惡化。",
            3,
        ),
        spec(
            36,
            "advanced",
            "不下注決策",
            STATUS_DONE,
            ["投注決策", "資料質素", "賽事狀態"],
            ["src/racing_model/betting.py", "src/racing_model/web/app.js"],
            "已對弱 EV、弱 edge、已開跑、已完場及資料不足候選輸出不下注/不可下注。",
            "仍需要 race-level 無 edge 判斷、資料噪音信心分及相關曝險後的整場不下注。",
            "加入全場 edge summary，模型無明顯優勢或曝險過度集中時直接建議不下注。",
            ["不是場場買", "無 edge 不買", "少數高質機會"],
            "極高：識得不下注係長期 ROI 核心。",
            "no-bet gate 要提升 ROI/回撤，不能靠排除虧損賽後資料。",
            1,
        ),
    ]
    return [item(**row) for row in rows]


def spec(
    item_id: int,
    category: str,
    name: str,
    status: str,
    data_sources: list[str],
    supported_files: list[str],
    current_support: str,
    gaps: str,
    next_steps: str,
    sub_items: list[str],
    model_risk: str,
    validation_gate: str,
    priority: int,
) -> dict[str, Any]:
    return {
        "item_id": item_id,
        "category": category,
        "name": name,
        "status": status,
        "data_sources": data_sources,
        "supported_files": supported_files,
        "current_support": current_support,
        "gaps": gaps,
        "next_steps": next_steps,
        "sub_items": sub_items,
        "model_risk": model_risk,
        "validation_gate": validation_gate,
        "priority": priority,
    }


def item(
    item_id: int,
    category: str,
    name: str,
    status: str,
    data_sources: list[str],
    supported_files: list[str],
    current_support: str,
    gaps: str,
    next_steps: str,
    sub_items: list[str],
    model_risk: str,
    validation_gate: str,
    priority: int,
) -> dict[str, Any]:
    return {
        "id": item_id,
        "category": category,
        "category_label": "核心方程式主項" if category == "core" else "進階實戰主項",
        "name": name,
        "status": status,
        "status_key": status_key(status),
        "data_sources": data_sources,
        "supported_files": supported_files,
        "current_support": current_support,
        "gaps": gaps,
        "next_steps": next_steps,
        "sub_items": sub_items,
        "model_risk": model_risk,
        "validation_gate": validation_gate,
        "priority": priority,
    }


def status_key(status: str) -> str:
    return {
        STATUS_DONE: "done",
        STATUS_PARTIAL: "partial",
        STATUS_MISSING: "missing",
        STATUS_EXTERNAL: "external",
    }[status]
